% Options for packages loaded elsewhere
% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\PassOptionsToPackage{dvipsnames,svgnames,x11names}{xcolor}
%
\documentclass[
]{article}
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{5}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
% Make \paragraph and \subparagraph free-standing
\makeatletter
\ifx\paragraph\undefined\else
  \let\oldparagraph\paragraph
  \renewcommand{\paragraph}{
    \@ifstar
      \xxxParagraphStar
      \xxxParagraphNoStar
  }
  \newcommand{\xxxParagraphStar}[1]{\oldparagraph*{#1}\mbox{}}
  \newcommand{\xxxParagraphNoStar}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
  \let\oldsubparagraph\subparagraph
  \renewcommand{\subparagraph}{
    \@ifstar
      \xxxSubParagraphStar
      \xxxSubParagraphNoStar
  }
  \newcommand{\xxxSubParagraphStar}[1]{\oldsubparagraph*{#1}\mbox{}}
  \newcommand{\xxxSubParagraphNoStar}[1]{\oldsubparagraph{#1}\mbox{}}
\fi
\makeatother


\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother


% definitions for citeproc citations
\NewDocumentCommand\citeproctext{}{}
\NewDocumentCommand\citeproc{mm}{%
  \begingroup\def\citeproctext{#2}\cite{#1}\endgroup}
\makeatletter
 % allow citations to break across lines
 \let\@cite@ofmt\@firstofone
 % avoid brackets around text for \cite:
 \def\@biblabel#1{}
 \def\@cite#1#2{{#1\if@tempswa , #2\fi}}
\makeatother
\newlength{\cslhangindent}
\setlength{\cslhangindent}{1.5em}
\newlength{\csllabelwidth}
\setlength{\csllabelwidth}{3em}
\newenvironment{CSLReferences}[2] % #1 hanging-indent, #2 entry-spacing
 {\begin{list}{}{%
  \setlength{\itemindent}{0pt}
  \setlength{\leftmargin}{0pt}
  \setlength{\parsep}{0pt}
  % turn on hanging indent if param 1 is 1
  \ifodd #1
   \setlength{\leftmargin}{\cslhangindent}
   \setlength{\itemindent}{-1\cslhangindent}
  \fi
  % set entry spacing
  \setlength{\itemsep}{#2\baselineskip}}}
 {\end{list}}
\usepackage{calc}
\newcommand{\CSLBlock}[1]{\hfill\break\parbox[t]{\linewidth}{\strut\ignorespaces#1\strut}}
\newcommand{\CSLLeftMargin}[1]{\parbox[t]{\csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLRightInline}[1]{\parbox[t]{\linewidth - \csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLIndent}[1]{\hspace{\cslhangindent}#1}



\setlength{\emergencystretch}{3em} % prevent overfull lines

\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}



 


\usepackage{array}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{amsmath}
\usepackage{amssymb}
\usepackage{textcomp}
\usepackage{fontspec}
\setmainfont{Latin Modern Roman}
\usepackage{newunicodechar}
\newunicodechar{ε}{\ensuremath{\varepsilon}}
\usepackage{authblk}
\renewcommand\Authfont{\normalsize}
\renewcommand\Affilfont{\small\itshape}
% Force tables to appear exactly where placed (prevent float drift)
\usepackage{float}
\floatplacement{table}{H}
% Center longtables
\setlength{\LTleft}{\fill}
\setlength{\LTright}{\fill}
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\AtBeginDocument{%
\ifdefined\contentsname
  \renewcommand*\contentsname{Table of contents}
\else
  \newcommand\contentsname{Table of contents}
\fi
\ifdefined\listfigurename
  \renewcommand*\listfigurename{List of Figures}
\else
  \newcommand\listfigurename{List of Figures}
\fi
\ifdefined\listtablename
  \renewcommand*\listtablename{List of Tables}
\else
  \newcommand\listtablename{List of Tables}
\fi
\ifdefined\figurename
  \renewcommand*\figurename{Figure}
\else
  \newcommand\figurename{Figure}
\fi
\ifdefined\tablename
  \renewcommand*\tablename{Table}
\else
  \newcommand\tablename{Table}
\fi
}
\@ifpackageloaded{float}{}{\usepackage{float}}
\floatstyle{ruled}
\@ifundefined{c@chapter}{\newfloat{codelisting}{h}{lop}}{\newfloat{codelisting}{h}{lop}[chapter]}
\floatname{codelisting}{Listing}
\newcommand*\listoflistings{\listof{codelisting}{List of Listings}}
\makeatother
\makeatletter
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\@ifpackageloaded{subcaption}{}{\usepackage{subcaption}}
\makeatother
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Hippocampal-to-Ventricle Ratio as a Head-Size-Independent Biomarker: Sex Differences and Cognitive Associations in 27,680 UK Biobank Participants},
  pdfauthor={Sofia Fernandez-Lozano; D. Louis Collins},
  pdfkeywords={Hippocampus, Lateral Ventricles, Sex
Characteristics, Magnetic Resonance Imaging, Cognitive
Aging, Biomarkers, Reference Values},
  colorlinks=true,
  linkcolor={blue},
  filecolor={Maroon},
  citecolor={Blue},
  urlcolor={Blue},
  pdfcreator={LaTeX via pandoc}}


% title.tex — Quarto template partial for author + affiliation rendering
\title{Hippocampal-to-Ventricle Ratio as a Head-Size-Independent
Biomarker: Sex Differences and Cognitive Associations in 27,680 UK
Biobank Participants}

\author[1,2]{Sofia
Fernandez-Lozano\thanks{ORCID: \href{https://orcid.org/0000-0003-2288-8111}{0000-0003-2288-8111}}}
\author[1,2,3]{D. Louis
Collins\thanks{ORCID: \href{https://orcid.org/0000-0002-8432-7021}{0000-0002-8432-7021}. Corresponding author: louis.collins@mcgill.ca}}

\affil[1]{Montreal Neurological Institute, McConnell Brain Imaging
Centre, Montreal, Quebec, Canada}
\affil[2]{Department of Neurology and Neurosurgery, McGill
University, Montreal, Quebec, Canada}
\affil[3]{Department of Biomedical Engineering, McGill
University, Montreal, Quebec, Canada}

\date{2026-08-03}

% Running head (HBM requires a short running title of < 40 characters)
\usepackage{fancyhdr}
\pagestyle{fancy}
\fancyhf{}
\fancyhead[L]{\small\itshape HVR Sex Differences in UK Biobank}
\fancyhead[R]{\small\thepage}
\renewcommand{\headrulewidth}{0.4pt}
\fancypagestyle{plain}{%
  \fancyhf{}%
  \fancyhead[L]{\small\itshape HVR Sex Differences in UK Biobank}%
  \fancyhead[R]{\small\thepage}%
  \renewcommand{\headrulewidth}{0.4pt}%
}

\begin{document}
\maketitle
\begin{abstract}
\textbf{Introduction:} Hippocampal volume is a key biomarker for
Alzheimer's disease and brain aging, yet reported sex differences vary
substantially depending on head-size adjustment methods. We examined
whether the hippocampal-to-ventricle ratio (HVR), a self-normalizing
measure, provides more consistent sex difference estimates than
conventional adjustment approaches. \textbf{Methods:} Using a subset of
UK Biobank structural MRI data (N = 27,680; 56.2\% female; ages 45--82),
we compared sex differences across four adjustment methods (unadjusted,
proportions, stereotaxic, residualized) and in samples matched on age
and on intracranial volume (ICV). Cross-sectional age patterns were
modeled with GAMLSS, and brain--cognition associations were estimated
via structural equation modeling on a bifactor cognitive model.
\textbf{Results:} Hippocampal sex differences reversed direction across
methods, ranging from \(d = -0.89\) (males larger, unadjusted) to
\(d = 0.58\) (females larger, proportions), with a range of 1.5 standard
deviations across analytical choices. In contrast, HVR showed a
consistent female advantage (\(d = 0.52\)) that persisted in the
ICV-matched subsample (\(d = 0.18\)), confirming this effect is not a
head-size artifact. Males exhibited steeper cross-sectional age-related
HVR differences (\(1.7\times\) female rate, \(p < 10^{-50}\)),
consistent with males showing ventricular expansion at younger ages. HVR
predicted general cognition comparably to hippocampal volume
(\(\beta = 0.04\), overlapping CIs), and unlike residualized hippocampal
volume, HVR maintained significant brain--cognition associations in both
sexes. \textbf{Conclusion:} Apparent hippocampal sex differences largely
reflect methodological choices rather than biology, while HVR captures
consistent morphological variation related to brain aging that may have
clinical utility. We provide sex-specific normative centile curves for
clinical application.
\end{abstract}


\textbf{Keywords:} hippocampus, lateral ventricles, sex characteristics,
magnetic resonance imaging, cognitive aging, biomarkers, reference
values

\section*{Key Points}\label{key-points}
\addcontentsline{toc}{section}{Key Points}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Hippocampal sex differences reverse direction depending on head-size
  adjustment method, spanning 1.5 SD across analytical choices.
\item
  The hippocampal-to-ventricle ratio (HVR) provides consistent sex
  difference estimates without requiring head-size correction and
  predicts cognition comparably to adjusted hippocampal volume.
\item
  Males show steeper cross-sectional age-related HVR reductions;
  sex-specific normative centile curves are provided for clinical
  application.
\end{enumerate}

\section{Introduction}\label{introduction}

The hippocampus (HC) is a brain structure used as an early biomarker for
Alzheimer's disease (AD) and brain aging (Jack et al., 1999, 2010; Raz
et al., 2005). Sex differences in brain structures have been documented,
but their interpretation is controversial (Ritchie et al., 2018; Ruigrok
et al., 2014), largely because findings depend on whether and how
head-size adjustments are applied (Nordenskjöld et al., 2015;
Sanchis-Segura et al., 2020). Males have approximately 12\% larger
intracranial volume (ICV) than females (Ruigrok et al., 2014), and after
head-size correction, sex classification from brain features drops from
\textgreater80\% to approximately 60\% (Sanchis-Segura et al., 2020).
This methodological sensitivity suggests some reported sex differences
may be artifacts of adjustment methods.

Hippocampal atrophy rates predict conversion from mild cognitive
impairment to dementia (Rajagopal et al., 2024), making accurate volume
assessment clinically consequential. However, males and females show
different rates of age-related brain volume change, with steeper
subcortical volume declines in males across multiple structures (Ritchie
et al., 2018). These sex-differential trajectories mean that normative
reference values must be sex-stratified to avoid misclassifying normal
variation as pathological; recent large-scale brain charting efforts
have adopted sex-specific centile modeling for this reason (Bethlehem et
al., 2022; Ge et al., 2024).

Multiple adjustment methods exist, each with different assumptions:
proportions (V/ICV) assumes perfect allometric scaling, residualization
(V \(-\) \(\beta \times\) ICV) removes linear ICV association, and
stereotaxic normalization applies spatial transformation to a template.
These methods can yield contradictory conclusions about the same brain
regions (Wang et al., 2024). For hippocampus, reported sex differences
range from males larger (unadjusted; Ruigrok et al. (2014)) to females
larger (proportions; Sanchis-Segura et al. (2020)) to no difference
(residualized; O'Brien et al. (2011)). The proportions method can
produce biologically implausible results, while residualization yields
more consistent estimates (Wang et al., 2024). No consensus exists on
the correct method, and conclusions depend on analytical choices.

The hippocampal-to-ventricle ratio (HVR), defined as HC / (HC + LV)
where HC denotes total hippocampal volume and LV denotes the volume of
the temporal horns of the lateral ventricles, offers a potential
solution. Both structures scale with head size, making their ratio
self-normalizing. HVR captures the relationship between hippocampal and
ventricular volumes, which show opposite patterns with age---smaller
hippocampus and larger ventricles. Schoemaker and colleagues introduced
HVR and showed that it provides stronger associations with age and
memory than standard hippocampal volume in healthy aging (Schoemaker et
al., 2019). Subsequent work shows HVR provides higher effect sizes for
distinguishing AD from controls compared to HC alone (Fernandez-Lozano
et al., 2025). However, properties of HVR in healthy populations and
across adjustment methods remain unexplored.

Age-related ventricular expansion reflects concurrent loss of
surrounding gray and white matter tissue (Madsen et al., 2015), and this
expansion occurs earlier in males, with abnormal enlargement appearing
in the seventies and preferentially affecting the frontal horns (Currà
et al., 2019). These sex-differential ventricular trajectories suggest
that a ratio incorporating both hippocampal and ventricular volumes may
capture sex differences in brain aging that individual volumes miss.
Furthermore, brain structure--cognition associations themselves may
differ by sex: grey matter volumes predict cognitive profiles with
different strength and spatial specificity in older males versus females
(Jockwitz et al., 2024), and hippocampal volume predicts associative
memory in older women but not men (Zheng et al., 2017). Whether HVR
shows similar sex-differential cognitive associations remains unknown.

We addressed three questions: (1) Do hippocampal sex differences vary
across head-size adjustment methods while HVR remains consistent? (2) Do
cross-sectional age patterns differ by sex, and do these patterns differ
between HC and HVR depending on normalization method? (3) Does HVR show
comparable cognitive associations to conventionally adjusted hippocampal
volumes?

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\section{Materials and Methods}\label{materials-and-methods}

\subsection{Data Source and
Participants}\label{data-source-and-participants}

Data were obtained from UK Biobank (Application 45551) (Miller et al.,
2016; Sudlow et al., 2015). The initial imaging sample comprised 42,898
participants with T1-weighted structural MRI. After exclusions (detailed
below), the final analytic sample included N = 27,680 participants aged
44.6 to 82.8 years. With this sample size, we had \textgreater99\% power
to detect small effects (d = 0.10) and \textgreater80\% power to detect
very small effects (d = 0.05) for two-group comparisons at \(\alpha\) =
.05.

Three additional subsamples were defined for specific analyses
(Figure~\ref{fig-prisma}; Table~\ref{tbl-demographics}). The
\textbf{England subsample} (N = 25,172) comprised participants assessed
at UK Biobank centres in England and was used for SEM analyses requiring
the Index of Multiple Deprivation (IMDP), which is not comparable across
UK countries. This subsample provides adequate power for detecting
standardized path coefficients \(\geq\) 0.02. The \textbf{ICV-matched
subsample} (N = 9,500) comprised female--male pairs matched on age
(\(\pm 1\) year) and ICV (\(\pm 25\) cc) drawn from the primary sample,
and was used to isolate sex effects from head-size confounding (see
Section~\ref{sec-sex-diff-methods}). The \textbf{longitudinal subsample}
(N = 2,935) comprised participants from the primary sample who also had
a follow-up imaging session (ses-3), with a mean intersession interval
of 2.7 years (SD = 1.1; range: 1.5--5.0). This subsample was used as a
sensitivity check for normative model calibration (see
Section~\ref{sec-age-patterns-methods}).

\subsubsection{Exclusion Criteria}\label{exclusion-criteria}

Participants were excluded if they had any of the following ICD-10
diagnoses recorded in linked hospital records: F00-F99 (mental and
behavioral disorders including dementia, mood disorders, schizophrenia,
and anxiety disorders, which are associated with hippocampal volume
alterations (Brosch et al., 2022; Cao et al., 2023; Schmaal et al.,
2016)); G00-G99 (neurological diseases including Parkinson's disease,
multiple sclerosis, epilepsy, and cerebrovascular disease, which
directly affect brain structure (Erp et al., 2016; Koenig et al., 2014;
Tai et al., 2025; Xu et al., 2020)); and Q00-Q07 (congenital CNS
malformations affecting normal brain development). This exclusion
strategy selected a sample of cognitively healthy adults without
conditions known to affect hippocampal morphometry. The full exclusion
flow is shown in Figure~\ref{fig-prisma}.

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{figures/fig-prisma.pdf}}

}

\caption{\label{fig-prisma}\textbf{Participant selection flow.} All
counts are unique participants; F and M values give female and male
sub-counts at each stage. Dashed boxes indicate analytic subsamples
derived from the GAMLSS sample.}

\end{figure}%

\subsubsection{Quality Control}\label{quality-control}

Image segmentations underwent quality control in three stages: (1)
automated quality scores from deep learning-based assessments, requiring
DARQ score \(\geq\) 0.25 (Fonov et al., 2022) and AssemblyNet rating of
``A'' (highest quality grade) (Coupé et al., 2020), (2) statistical
outlier detection excluding participants with age- and
head-size-adjusted volumes exceeding \(\pm 3\) SD from the sample mean,
and (3) visual inspection of flagged cases by trained raters for evident
segmentation failures, motion artifacts, or anatomical anomalies. This
multi-stage pipeline is intentionally conservative: in a large
population-based study where statistical power is not a limiting factor,
prioritizing data quality over sample retention reduces the risk of
segmentation errors biasing volumetric estimates, particularly for small
structures like the hippocampus and temporal horn ventricles where even
minor segmentation failures can produce large relative errors.

For participants with multiple imaging sessions, QC filtering was
applied first, then one session per participant was selected for
cross-sectional analyses. When a participant's baseline session (ses-2)
failed QC but the follow-up session (ses-3) passed, the follow-up
session was retained in the cross-sectional sample. Longitudinal
analyses required both sessions to pass QC.

\subsection{Brain Measures}\label{brain-measures}

\subsubsection{Image Acquisition}\label{image-acquisition}

Images were acquired on Siemens Skyra 3T scanners at three UK sites
(Cheadle, Newcastle, Reading) using a T1-weighted MPRAGE sequence at 1mm
isotropic resolution. Full protocol details are provided in
Alfaro-Almagro et al. (2018).

\subsubsection{Segmentation}\label{segmentation}

Hippocampal and ventricular volumes were segmented using an in-house
convolutional neural network trained on manually labeled data.
Validation against manual segmentations showed Dice \(\kappa\) = 0.94
and Spearman's \(\rho\) = 0.99 (Fernandez-Lozano et al., 2025). Outputs
included bilateral hippocampal volumes (left, right, total) and temporal
horn volumes of the lateral ventricles (left, right, total).
Intracranial volume (ICV) was obtained from AssemblyNet (Coupé et al.,
2020), a large-ensemble convolutional neural network for whole-brain MRI
segmentation.

\subsubsection{Head-Size Adjustment
Methods}\label{head-size-adjustment-methods}

Four adjustment approaches were applied to hippocampal and ventricular
volumes (Sanchis-Segura et al., 2020; Sanfilipo et al., 2004):

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  \textbf{Unadjusted}: raw volumes in native space (mL), which preserve
  natural variation but are confounded by overall head size.
\item
  \textbf{Proportions}: volume expressed as a proportion of ICV, which
  assumes isometric (1:1) scaling and may over- or under-correct
  depending on the true allometric relationship (Jong et al., 2017;
  Williams et al., 2021):
\end{enumerate}

\begin{equation}\phantomsection\label{eq-prp}{V_{\text{PRP}} = \frac{V}{\text{ICV}} \times 1000}\end{equation}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  \textbf{Stereotaxic}: volumes in standard template space after
  nonlinear registration, which corrects for global size and shape
  differences:
\end{enumerate}

\begin{equation}\phantomsection\label{eq-stx}{V_{\text{STX}} = V \times |J|}\end{equation}
where \(J\) is the Jacobian determinant of the nonlinear transformation.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{3}
\tightlist
\item
  \textbf{Residualized}: linear regression residuals after removing ICV
  association, with regression coefficients estimated from the pooled
  sample (O'Brien et al., 2011; Sanchis-Segura et al., 2020):
\end{enumerate}

\begin{equation}\phantomsection\label{eq-res}{V_{\text{RES}} = V - \hat{\beta} \times (\text{ICV} - \overline{\text{ICV}})}\end{equation}

Residualization eliminates ICV-related variance and produces more
replicable sex differences compared to proportional methods.

\subsubsection{HVR Calculation}\label{hvr-calculation}

The hippocampal-to-ventricle ratio (HVR) was computed as:

\begin{equation}\phantomsection\label{eq-hvr}{\text{HVR} = \frac{\text{HC}_{\text{total}}}{\text{HC}_{\text{total}} + \text{LV}_{\text{total}}}}\end{equation}
where \(\text{HC}_{\text{total}}\) and \(\text{LV}_{\text{total}}\)
denote bilateral sums (left + right) of hippocampal and lateral
ventricular temporal horn volumes, respectively. HVR is bounded between
0 and 1, with higher values indicating larger hippocampus relative to
ventricles. Because HVR is a ratio of two head-size-dependent
structures, no further head-size adjustment was applied.

\subsection{Cognitive Assessment}\label{cognitive-assessment}

\subsubsection{Test Battery}\label{test-battery}

Cognitive data were collected at the imaging visit using the UK Biobank
touchscreen-based cognitive battery (Sudlow et al., 2015), comprising 12
indicators spanning memory, processing speed, executive function, and
reasoning domains (Supporting Information, Table S1). Timed measures
(reaction time, trail making, pair matching response time) were
inverse-coded so that higher scores consistently indicate better
performance across all indicators. Missing cognitive data were handled
using full information maximum likelihood (FIML) estimation, which uses
all available data under a missing-at-random assumption.

\subsubsection{Factor Structure: Bifactor
CFA}\label{factor-structure-bifactor-cfa}

Cognitive indicators were modeled using a bifactor confirmatory factor
analysis (CFA) with three latent factors. The general factor (\emph{g})
loaded on all 12 indicators. The memory-specific factor
(Memory\textsubscript{s}, orthogonal to \emph{g}) loaded on pair
matching, numeric memory, and prospective memory. The processing
speed-specific factor (Speed\textsubscript{s}, orthogonal to \emph{g})
loaded on reaction time, trail making numeric, and symbol digit
substitution correct. Factor scales were set using the marker variable
method (first loading fixed to 1.0 for each factor). All latent factors
were constrained to be orthogonal, consistent with bifactor model
assumptions. Cross-loadings were fixed to zero. Residual covariances
were specified for indicator pairs sharing method variance within the
same test (pair matching time with errors; symbol digit correct with
attempts; trail making numeric with alphanumeric).

Models were estimated using maximum likelihood with robust standard
errors (MLR) in lavaan (Rosseel, 2012).

\subsection{Statistical Analyses}\label{statistical-analyses}

\subsubsection{Sex Differences Across Adjustment
Methods}\label{sec-sex-diff-methods}

\paragraph{HVR Self-Normalizing
Properties}\label{hvr-self-normalizing-properties}

To evaluate whether HVR reduces head-size confounding, we computed
Pearson correlations between ICV and each brain measure (HC, LV, HVR) as
well as between ICV and each head-size adjusted HC volume (proportions,
stereotaxic, residualized). We expected a self-normalizing measure to
show reduced correlation with ICV compared to unadjusted volumes.

\paragraph{Sex Differences in Brain
Measures}\label{sex-differences-in-brain-measures}

Sex differences were quantified using Cohen's d with 95\% confidence
intervals (Cohen, 2013), with positive d indicating females
\textgreater{} males by our coding convention. Effect sizes were
computed for all ROI × adjustment method combinations in the full sample
(N = 27,680).

To isolate sex effects from head-size confounding, we created an
ICV-matched subsample where females and males were paired on age
(\(\pm 1\) year) and ICV (\(\pm 25\) cc, approximately 0.3 SD). Matching
used the MatchIt package (v4.7.2; Ho et al. (2011)) with optimal 1:1
matching without replacement (\texttt{method\ =\ "optimal"},
\texttt{distance\ =\ "mahalanobis"}), with calipers (the maximum
permitted within-pair difference) set to the age and ICV tolerances
above. This yielded N = 4,750 matched pairs (total N = 9,500). We
reasoned that if sex differences in HC persist after matching on ICV,
they cannot be attributed solely to head-size confounding, and if HVR
shows similar effects in full and matched samples, this indicates HVR is
independent of head size.

\subsubsection{Age-Related Patterns and Normative
Modeling}\label{sec-age-patterns-methods}

\paragraph{Age × Sex Interactions}\label{age-sex-interactions}

Linear regression models tested whether cross-sectional age-related
patterns differed by sex:

\begin{equation}\phantomsection\label{eq-age-sex}{Y_i = \beta_0 + \beta_{\text{Age}} \cdot \text{Age}_i + \beta_{\text{Sex}} \cdot \text{Sex}_i + \beta_{\text{Age} \times \text{Sex}} \cdot \text{Age}_i \times \text{Sex}_i + \varepsilon_i}\end{equation}
where \(Y\) is the brain measure, Sex is coded as a binary indicator
(Female = reference), and
\(\varepsilon_i \sim \mathcal{N}(0, \sigma^2)\). A significant
\(\beta_{\text{Age} \times \text{Sex}}\) indicates different age slopes
between sexes. Sex-specific slopes were derived as
\(\hat{\beta}_{\text{Age}}\) for females and
\(\hat{\beta}_{\text{Age}} + \hat{\beta}_{\text{Age} \times \text{Sex}}\)
for males, and their ratio quantified the relative rate of
cross-sectional age-related differences. Separate models were fit for
HC\textsubscript{RES} and LV\textsubscript{RES} (both residualized
against ICV; Equation~\ref{eq-res}) and HVR (self-normalizing;
Equation~\ref{eq-hvr}). Scanner site was not included as a random effect
given the low site ICCs (\textless{} 0.05; see Sensitivity Analyses),
indicating minimal site contribution to variance. While age trajectories
may be non-linear (as captured by the GAMLSS normative models below),
linear interaction models were used here to provide interpretable
summary statistics for sex-differential aging rates.

\paragraph{Normative Centile Curves}\label{normative-centile-curves}

Sex-specific normative centile curves were estimated using Generalized
Additive Models for Location, Scale, and Shape (GAMLSS) (Bethlehem et
al., 2022; Rigby \& Stasinopoulos, 2005) on the N = 27,434 participants
from the primary sample with complete education and site data. For HC
and LV (unadjusted):

\begin{equation}\phantomsection\label{eq-gamlss-hc}{\mu = f_\mu(\text{Age}) + \beta_{\text{ICV}} \cdot \text{ICV} + \beta_{\text{Edu}} \cdot \text{Education} + u_{\text{site}}}\end{equation}

For HVR (self-normalizing, no ICV term needed):

\begin{equation}\phantomsection\label{eq-gamlss-hvr}{\mu = f_\mu(\text{Age}) + \beta_{\text{Edu}} \cdot \text{Education} + u_{\text{site}}}\end{equation}
where \(f_\mu(\cdot)\) denotes a cubic spline smooth for the location
parameter and \(u_{\text{site}}\) denotes random intercepts for scanner
site. Although site ICCs were low (\textless{} 0.05; see Sensitivity
Analyses), site random intercepts were retained in the normative models
because centile estimation targets individual-level classification,
where even small systematic shifts can affect percentile assignment. The
scale parameter was also modeled as a function of age,
\(\sigma = f_\sigma(\text{Age})\), allowing variance to change across
the age range. Model families (Gaussian and Box-Cox Cole and Green;
BCCG) were compared using AIC, with BIC as secondary criterion. The BCCG
distribution was used when flexible modeling of location (\(\mu\)),
scale (\(\sigma\)), and skewness (\(\nu\)) was warranted; shape
parameters beyond \(\sigma\) were held constant to maintain parsimony.
Centile curves (5th, 10th, 25th, 50th, 75th, 90th, 95th) were generated
for ages 45--82 by sex.

Data were split into 80\% training and 20\% test sets, stratified by sex
and 5-year age bins, to evaluate model fit on independent data and guard
against overfitting. Distribution families were selected on training
data and evaluated on the held-out test set by comparing observed
vs.~expected proportions across centiles. Final models were then fit on
the complete cross-sectional sample using the selected distribution
family. Model calibration was additionally assessed using the
longitudinal subsample (N = 2,935; see Data Source and Participants).
Because this subsample comprises the same participants as the primary
cross-sectional sample with an additional follow-up session, it tests
temporal stability rather than independent validation. Test-retest
reliability was quantified using Pearson correlation and intraclass
correlation coefficient (ICC, two-way random, absolute agreement).

Two sets of GAMLSS models were generated: (1) site-controlled models
including random site intercepts (\(u_{\text{site}}\)) for optimal
within-UKB accuracy, and (2) transfer models without site effects for
application to external cohorts where site is unknown or not comparable.
Transfer models used identical distribution families but omitted the
random site term, following recommendations for cross-study normative
modeling.

\subsubsection{Brain-Cognition
Associations}\label{brain-cognition-associations}

Joint measurement-structural equation models tested associations between
brain measures and cognitive factors. These analyses were restricted to
the England subsample (N = 25,172; see Data Source and Participants)
because the Index of Multiple Deprivation (IMDP), used as a
socioeconomic covariate, is not comparable across UK countries. All
models were estimated in lavaan (Rosseel, 2012).

\paragraph{Measurement Invariance}\label{measurement-invariance}

Comparing brain-cognition associations across sexes requires that the
cognitive measurement model is equivalent across groups. Measurement
invariance of the bifactor structure (see Factor Structure: Bifactor
CFA) was therefore tested following standard multi-group CFA procedures
(Putnick \& Bornstein, 2016). Four nested models were tested: (1)
configural invariance (same factor structure), (2) metric invariance
(equal loadings), (3) scalar invariance (equal intercepts), and (4)
strict invariance (equal residuals). Invariance was evaluated using
\(\Delta\)CFI \(\leq\) 0.01 (Cheung \& Rensvold, 2002) and
\(\Delta\)RMSEA \(\leq\) 0.015 (Chen, 2007). At minimum, metric
invariance is required to compare structural paths across groups.

\paragraph{SEM Specifications}\label{sem-specifications}

Given adequate measurement invariance, three SEM models were estimated,
each combining the bifactor cognitive measurement model with structural
paths from a brain measure to all three cognitive factors. Brain
measures entered as observed (manifest) variables: HC (bilateral
hippocampal volume, sum of left and right), HVR (Equation~\ref{eq-hvr}),
and HC\textsubscript{RES} (HC residualized against ICV within sex,
yielding r \(\approx\) 0 with ICV by construction). The structural
component of each model took the following form:

\textbf{Model 1 (HC):}

\begin{equation}\phantomsection\label{eq-sem-hc}{\begin{aligned}
\text{HC} &= \beta_{\text{Age}} \cdot \text{Age} + \beta_{\text{ICV}} \cdot \text{ICV} + \beta_{\text{Edu}} \cdot \text{Edu} + \beta_{\text{IMDP}} \cdot \text{IMDP} + \zeta_{\text{HC}} \\
\eta_k &= \beta_{k,\text{HC}} \cdot \text{HC} + \beta_{k,\text{Age}} \cdot \text{Age} + \beta_{k,\text{ICV}} \cdot \text{ICV} + \beta_{k,\text{Edu}} \cdot \text{Edu} + \beta_{k,\text{IMDP}} \cdot \text{IMDP} + \zeta_k
\end{aligned}}\end{equation}

\textbf{Model 2 (HVR):}

\begin{equation}\phantomsection\label{eq-sem-hvr}{\begin{aligned}
\text{HVR} &= \beta_{\text{Age}} \cdot \text{Age} + \beta_{\text{Age}^2} \cdot \text{Age}^2 + \beta_{\text{ICV}} \cdot \text{ICV} \\
  &\quad + \beta_{\text{Edu}} \cdot \text{Edu} + \beta_{\text{IMDP}} \cdot \text{IMDP} + \zeta_{\text{HVR}} \\
\eta_k &= \beta_{k,\text{HVR}} \cdot \text{HVR} + \beta_{k,\text{Age}} \cdot \text{Age} + \beta_{k,\text{Age}^2} \cdot \text{Age}^2 \\
  &\quad + \beta_{k,\text{ICV}} \cdot \text{ICV} + \beta_{k,\text{Edu}} \cdot \text{Edu} + \beta_{k,\text{IMDP}} \cdot \text{IMDP} + \zeta_k
\end{aligned}}\end{equation}

\textbf{Model 3 (HC\textsubscript{RES}):}

\begin{equation}\phantomsection\label{eq-sem-hcres}{\begin{aligned}
\text{HC}_{\text{RES}} &= \beta_{\text{Age}} \cdot \text{Age} + \beta_{\text{Age}^2} \cdot \text{Age}^2 + \beta_{\text{ICV}} \cdot \text{ICV} \\
  &\quad + \beta_{\text{Edu}} \cdot \text{Edu} + \beta_{\text{IMDP}} \cdot \text{IMDP} + \zeta_{\text{HC}_{\text{RES}}} \\
\eta_k &= \beta_{k,\text{HC}_{\text{RES}}} \cdot \text{HC}_{\text{RES}} + \beta_{k,\text{Age}} \cdot \text{Age} + \beta_{k,\text{Age}^2} \cdot \text{Age}^2 \\
  &\quad + \beta_{k,\text{ICV}} \cdot \text{ICV} + \beta_{k,\text{Edu}} \cdot \text{Edu} + \beta_{k,\text{IMDP}} \cdot \text{IMDP} + \zeta_k
\end{aligned}}\end{equation}

where \(\eta_k \in \{g, \text{Memory}_s, \text{Speed}_s\}\) denotes
latent cognitive factors and \(\zeta\) denotes residual terms. A
quadratic age term was included in the HVR and HC\textsubscript{RES}
models but not in the HC model, where the combination of raw hippocampal
volume, ICV, and quadratic age produced multicollinearity. This
difference in model specification means that brain-cognition path
comparisons between HC and the other measures should be interpreted with
this constraint in mind, as the HC model captures only linear age
effects. Age was centered within sex groups before squaring. All
structural variables were z-standardized within sex groups to address
scale differences. Covariates are summarized in Table S2.

The HC\textsubscript{RES} model serves as a benchmark representing the
methodological standard for removing head-size confounding. Comparing
HVR to HC\textsubscript{RES} tests whether HVR provides similar
cognitive associations while being self-normalizing and capturing
additional variance through its incorporation of ventricular dynamics.
The proportions and stereotaxic adjustment methods were excluded due to
concerns about biologically implausible associations and residual ICV
correlation, respectively (Wang et al., 2024).

\paragraph{Estimation and Inference}\label{estimation-and-inference}

Two estimation approaches were used. Pooled models combined all
participants, included sex as a covariate, and were estimated using
robust maximum likelihood (MLR) with cluster-robust standard errors to
account for scanner site. Multi-group models estimated separate
structural parameters for females and males, allowing sex differences in
brain-cognition paths to be directly tested; these were estimated using
maximum likelihood with bootstrap confidence intervals (2,000 resamples)
(Cumming \& Finch, 2005). Missing cognitive data were handled using full
information maximum likelihood (FIML) in both approaches. Sex
differences in path coefficients were evaluated by comparing bootstrap
confidence intervals across groups.

\subsubsection{Sensitivity Analyses}\label{sensitivity-analyses}

Three sensitivity analyses assessed the robustness of sex difference
findings to analytical choices.

\paragraph{Site effects}\label{site-effects}

Scanner site (UK Biobank assessment centre) can introduce systematic
variance in volumetric measurements due to differences in scanner
hardware, software versions, or acquisition protocols. Site effects were
quantified using the intraclass correlation coefficient:

\begin{equation}\phantomsection\label{eq-icc}{\text{ICC} = \frac{\sigma^2_{\text{site}}}{\sigma^2_{\text{site}} + \sigma^2_{\text{residual}}}}\end{equation}

Site-adjusted sex difference effect sizes were computed using linear
mixed-effects models with a fixed effect for sex and a random intercept
for scanner site:

\begin{equation}\phantomsection\label{eq-site-adj}{Y_i = \beta_0 + \beta_{\text{Sex}} \cdot \text{Sex}_i + u_{\text{site}(i)} + \varepsilon_i}\end{equation}
where \(u_{\text{site}} \sim \mathcal{N}(0, \sigma^2_{\text{site}})\)
and \(\varepsilon_i \sim \mathcal{N}(0, \sigma^2_{\text{residual}})\).
Cohen's d was approximated as
\(\hat{\beta}_{\text{Sex}} / \hat{\sigma}_{\text{residual}}\), with
confidence intervals derived from the Wald approximation.

\paragraph{Hemisphere comparison}\label{hemisphere-comparison}

Left and right hippocampus and lateral ventricle volumes (residualized
against ICV) were analyzed separately to assess whether sex differences
are lateralized. Cohen's d was computed for each hemisphere
independently, with effect size comparisons based on overlapping 95\%
confidence intervals. Non-overlapping intervals indicate a statistically
significant difference in effect magnitude between hemispheres.

\paragraph{Inclusion of psychiatric
diagnoses}\label{inclusion-of-psychiatric-diagnoses}

To assess robustness, sex difference analyses were repeated in an
expanded sensitivity sample that retained participants with F-code
diagnoses (F00-F99; N = 30,032) while still excluding G and Q0 codes.
The impact of psychiatric exclusion was quantified as \(\Delta d\) =
\(d_{\text{primary}}\) - \(d_{\text{sensitivity}}\).

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\section{Results}\label{results}

\subsection{Sample Characteristics}\label{sample-characteristics}

The primary sample comprised 27,680 participants (15,555 female, 12,125
male; 56.2\% female) aged 44.6--82.8 years
(Table~\ref{tbl-demographics}). Females were slightly younger on average
(M = 62.9, SD = 7.3) than males (M = 64.1, SD = 7.7). Males had
substantially larger ICV than females, consistent with the
well-documented sex difference in head size. The England subsample (N =
25,172), ICV-matched subsample (N = 9,500; 4,750 pairs), and
longitudinal subsample (N = 2,935) showed comparable age and ICV
distributions to the primary sample within their respective selection
constraints.

\begin{table}

\caption{\label{tbl-demographics}\textbf{Participant characteristics by
sex and sample.} Values are M (SD). d = Cohen's d (Female − Male).
England = English assessment centres (SEM analyses). Matched = age
\(\pm 1\) yr, ICV \(\pm 25\) cc. Longitudinal = participants with repeat
imaging.}

\centering{

\fontsize{7.0pt}{8.0pt}\selectfont
\begin{center}\renewcommand{\arraystretch}{1.15}\begin{tabular}{l|rrr}
\toprule
 & Females & Males & \emph{d} \\ 
\midrule\addlinespace[2.5pt]
\multicolumn{4}{l}{Primary} \\[2.5pt] 
\midrule\addlinespace[2.5pt]
n & 15,555 & 12,125 & \textemdash \\ 
Age, years & 62.9 (7.3) & 64.1 (7.7) & -0.16 \\ 
ICV, cc & 1503 (107) & 1719 (125) & -1.87 \\ 
\midrule\addlinespace[2.5pt]
\multicolumn{4}{l}{England} \\[2.5pt] 
\midrule\addlinespace[2.5pt]
n & 14,140 & 11,032 & \textemdash \\ 
Age, years & 62.9 (7.3) & 64.1 (7.7) & -0.16 \\ 
ICV, cc & 1503 (107) & 1719 (126) & -1.86 \\ 
\midrule\addlinespace[2.5pt]
\multicolumn{4}{l}{Matched} \\[2.5pt] 
\midrule\addlinespace[2.5pt]
n & 4,750 & 4,750 & \textemdash \\ 
Age, years & 63.5 (7.5) & 63.5 (7.6) & -0.00 \\ 
ICV, cc & 1610 (83) & 1612 (84) & -0.03 \\ 
\midrule\addlinespace[2.5pt]
\multicolumn{4}{l}{Longitudinal} \\[2.5pt] 
\midrule\addlinespace[2.5pt]
n & 1,691 & 1,253 & \textemdash \\ 
Age, years & 60.6 (7.0) & 61.6 (7.4) & -0.14 \\ 
ICV, cc & 1509 (107) & 1723 (130) & -1.82 \\ 
\bottomrule
\end{tabular}\end{center}

}

\end{table}%

\subsection{Sex Differences Across Adjustment
Methods}\label{sex-differences-across-adjustment-methods}

\subsubsection{HVR Self-Normalizing
Properties}\label{hvr-self-normalizing-properties-1}

Unadjusted HC showed strong positive correlation with ICV (r = 0.605),
while proportions-adjusted HC showed moderate negative correlation (r =
-0.39), indicating over-correction (Table~\ref{tbl-hvr-validation}).
Residualization eliminated ICV association by construction (r
\(\approx\) 0). HVR's correlation with ICV (r = -0.252) was smaller in
magnitude than raw HC (r = 0.605) but remained negative, unlike
residualized HC (r \(\approx\) 0). This represents a 58\% reduction in
absolute ICV association. This residual negative association arises
because the ventricular volume, which itself scales positively with head
size (LV-ICV r = 0.462), sits in the HVR denominator: larger heads yield
larger ventricles and, in turn, a lower HVR. The HVR-ICV association
therefore reflects the ventricular component's scaling with head size
rather than a residual hippocampal effect.

\begin{table}

\caption{\label{tbl-hvr-validation}\textbf{Brain measure correlations
with ICV.} An ideal self-normalizing measure shows r(ICV) near zero.}

\centering{

\fontsize{7.0pt}{8.0pt}\selectfont
\begin{center}\renewcommand{\arraystretch}{1.15}\begin{tabular}{lrr}
\toprule
Measure & r(ICV) & 95\% CI \\ 
\midrule\addlinespace[2.5pt]
\multicolumn{3}{l}{Hippocampus} \\[2.5pt] 
\midrule\addlinespace[2.5pt]
Unadjusted & 0.605 & [0.597, 0.612] \\ 
Proportions & -0.390 & [-0.400, -0.380] \\ 
Stereotaxic & -0.323 & [-0.333, -0.312] \\ 
Residualized & 0.000 & [-0.012, 0.012] \\ 
\midrule\addlinespace[2.5pt]
\multicolumn{3}{l}{Lateral Ventricles} \\[2.5pt] 
\midrule\addlinespace[2.5pt]
Unadjusted & 0.462 & [0.452, 0.471] \\ 
Proportions & 0.128 & [0.116, 0.139] \\ 
Stereotaxic & 0.134 & [0.122, 0.146] \\ 
Residualized & 0.000 & [-0.012, 0.012] \\ 
\midrule\addlinespace[2.5pt]
\multicolumn{3}{l}{Hippocampal-to-Ventricle Ratio} \\[2.5pt] 
\midrule\addlinespace[2.5pt]
Self-normalizing & -0.252 & [-0.263, -0.241] \\ 
\bottomrule
\end{tabular}\end{center}

}

\end{table}%

\subsubsection{Sex Differences in Brain
Measures}\label{sex-differences-in-brain-measures-1}

Sex differences varied across brain measures and adjustment methods (N =
27,680; Figure~\ref{fig-effect-sizes}).

\paragraph{Hippocampal Volume}\label{hippocampal-volume}

HC sex differences reversed direction depending on the adjustment
method. Unadjusted volumes showed d = -0.89 {[}95\% CI: -0.91, -0.86{]},
indicating males had larger absolute volumes. Proportions adjustment
reversed this to d = 0.58 {[}0.56, 0.6{]} with females larger.
Stereotaxic adjustment yielded d = 0.59 {[}0.56, 0.61{]}, and
residualized volumes showed a negligible effect (d = 0.02 {[}0,
0.05{]}). The effect size range across methods spanned 1.47 standard
deviations.

\paragraph{Lateral Ventricular Volume}\label{lateral-ventricular-volume}

Unlike HC, lateral ventricular sex differences were consistently
negative (males \textgreater{} females) across all adjustment methods,
though effect magnitudes were attenuated by head-size correction.
Unadjusted LV showed d = -0.84 {[}-0.86, -0.82{]}, similar in magnitude
to unadjusted HC. After adjustment, all methods retained the male
advantage: proportions d = -0.34 {[}-0.37, -0.32{]}, stereotaxic d =
-0.31 {[}-0.33, -0.28{]}, and residualized d = -0.16 {[}-0.19, -0.14{]}.
The directional consistency across methods contrasts with the reversals
observed for HC.

\paragraph{HVR}\label{hvr}

HVR showed a consistent female advantage: d = 0.52 {[}95\% CI: 0.49,
0.54{]}. Distribution overlap between sexes across adjustment methods is
shown in Supporting Information (Figure S2).

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{manuscript_files/figure-pdf/fig-effect-sizes-1.pdf}}

}

\caption{\label{fig-effect-sizes}\textbf{Sex differences by adjustment
method.} Circles = full sample; triangles = ICV-matched subsample. Faded
points indicate non-significant effects (95\% confidence interval
crosses zero). Right panel shows \(\Delta d\) = \(d_{\text{full}}\)
\(-\) \(d_{\text{matched}}\), representing the change in effect size
after removing head-size confounding; values near zero indicate
head-size-independent effects.}

\end{figure}%

\paragraph{Matched-Pair Comparison}\label{matched-pair-comparison}

Matching on age and ICV (N = 9,500; 4,750 pairs) revealed which sex
differences persist after removing head-size confounding
(Table~\ref{tbl-matched}). HC effects collapsed to near-zero (unadjusted
d = -0.04), confirming that HC sex differences are driven by head-size
variation. LV effects were attenuated but remained significant
(unadjusted d = -0.2), indicating that males have larger ventricles even
at equivalent head size. HVR was reduced but persisted (d = 0.18
{[}0.14, 0.22{]}), consistent with the female HVR advantage being
independent of head-size confounding.

\begin{table}

\caption{\label{tbl-matched}\textbf{Full vs.~ICV-matched subsample
effect sizes.} Matching on age (\(\pm 1\) yr) and ICV (\(\pm 25\) cc)
eliminates head-size confounding.}

\centering{

\fontsize{7.0pt}{8.0pt}\selectfont
\begin{center}\renewcommand{\arraystretch}{1.15}\begin{tabular}{l|rrrrrr}
\toprule
 & \multicolumn{2}{c}{Full Sample} & \multicolumn{2}{c}{Matched Sample} & \multicolumn{2}{c}{Difference} \\ 
\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}
Adjustment & d & 95\% CI & d & 95\% CI & \ensuremath{\Delta}d & 95\% CI \\ 
\midrule\addlinespace[2.5pt]
\multicolumn{7}{l}{Hippocampus} \\[2.5pt] 
\midrule\addlinespace[2.5pt]
Unadjusted & -0.885 & [-0.910, -0.860] & -0.038 & [-0.079, 0.002] & -0.847 & [-0.894, -0.799] \\ 
Proportions & 0.580 & [0.556, 0.605] & -0.022 & [-0.062, 0.018] & 0.602 & [0.556, 0.649] \\ 
Residuals & 0.022 & [-0.002, 0.046] & -0.030 & [-0.071, 0.010] & 0.053 & [0.006, 0.099] \\ 
Stereotaxic & 0.588 & [0.563, 0.612] & 0.154 & [0.114, 0.194] & 0.434 & [0.387, 0.481] \\ 
\midrule\addlinespace[2.5pt]
\multicolumn{7}{l}{Lateral Ventricles} \\[2.5pt] 
\midrule\addlinespace[2.5pt]
Unadjusted & -0.840 & [-0.865, -0.815] & -0.204 & [-0.245, -0.164] & -0.635 & [-0.683, -0.588] \\ 
Proportions & -0.341 & [-0.365, -0.317] & -0.203 & [-0.244, -0.163] & -0.138 & [-0.185, -0.091] \\ 
Residuals & -0.162 & [-0.185, -0.138] & -0.203 & [-0.243, -0.163] & 0.041 & [-0.005, 0.088] \\ 
Stereotaxic & -0.308 & [-0.332, -0.284] & -0.138 & [-0.178, -0.097] & -0.170 & [-0.217, -0.123] \\ 
\midrule\addlinespace[2.5pt]
\multicolumn{7}{l}{Hippocampus-to-Ventricle ratio} \\[2.5pt] 
\midrule\addlinespace[2.5pt]
Self-normalizing & 0.517 & [0.493, 0.542] & 0.183 & [0.142, 0.223] & 0.335 & [0.288, 0.382] \\ 
\bottomrule
\end{tabular}\end{center}

}

\end{table}%

\subsection{Age-Related Patterns and Normative
Modeling}\label{age-related-patterns-and-normative-modeling}

\subsubsection{Age × Sex Interactions}\label{age-sex-interactions-1}

Cross-sectional age patterns (N = 27,680) differed by sex
(Figure~\ref{fig-age-trajectory}). For HVR, the age × sex interaction
was significant (\(\beta\) = -0.001, SE = 0, t = -16.58, p = 2e-61),
with males showing 1.66× steeper cross-sectional age-related
differences. The female HVR advantage \emph{widened} with age---effect
sizes increased from d = 0.23 at ages 45-55 to d = 0.66 at ages 75+.

Age × sex interactions were significant for all three measures. HC
showed males with 1.63× steeper cross-sectional differences (p =
3.1e-10). LV showed the largest sex disparity, with males exhibiting
1.87× steeper ventricular expansion (p = 4.6e-80). The greater sex
disparity in ventricular age patterns compared to hippocampal age
patterns explains the intermediate HVR ratio (1.66×), as HVR captures
both processes.

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{manuscript_files/figure-pdf/fig-age-trajectory-1.pdf}}

}

\caption{\label{fig-age-trajectory}\textbf{Age-related patterns in sex
differences.} Solid line = hippocampal-to-ventricle ratio; dashed lines
= hippocampal/ventricular volume. White-filled points = non-significant
(95\% confidence interval crosses zero).}

\end{figure}%

\subsubsection{Normative Centile
Curves}\label{normative-centile-curves-1}

Figure~\ref{fig-normative-centiles} presents sex-specific normative
centiles for HVR, hippocampal volume, and lateral ventricular volume.
Across the age range, females showed higher HVR values at all percentile
levels; the median female HVR at age 55 corresponded approximately to
the 75th percentile for males of the same age. HC and LV centile curves
are generated from GAMLSS models that include ICV as a covariate,
providing head-size adjusted norms without pre-residualizing the data.
Males show greater ventricular variability at older ages, potentially
reflecting greater heterogeneity in aging patterns.

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{manuscript_files/figure-pdf/fig-normative-centiles-1.pdf}}

}

\caption{\label{fig-normative-centiles}\textbf{Sex-specific normative
centile curves.} Hippocampal-to-ventricle ratio (top), hippocampal
volume (middle), and lateral ventricular volume (bottom). Left and right
columns show female and male centiles separately; the centre column
overlays both sexes for direct comparison. Hippocampal and ventricular
volume models include intracranial volume as a covariate.}

\end{figure}%

Calibration plots (Supporting Information, Figure S1) assess whether the
normative models are well-specified: for each nominal centile (e.g., the
10th percentile curve), the plot shows what proportion of observations
actually fall below that curve. A well-calibrated model produces points
along the diagonal (observed proportion = expected proportion). Our
models closely track the diagonal across all centiles, indicating that
the fitted distributions accurately capture the true variability in the
data.

\paragraph{Temporal Stability (Longitudinal
Validation)}\label{temporal-stability-longitudinal-validation}

All brain measures demonstrated high test-retest reliability across the
longitudinal follow-up (Table S3), with Pearson correlations
\textgreater{} 0.95 and ICCs \textgreater{} 0.93 for all measures. HVR
showed slightly lower reliability (r = 0.952, ICC = 0.933) compared to
HC (r = 0.964, ICC = 0.959) and LV (r = 0.958, ICC = 0.946), consistent
with the ratio measure amplifying small measurement errors in either
component. These reliabilities support the use of these normative models
for individual-level assessment.

\paragraph{Clinical Normative Centile
Tables}\label{clinical-normative-centile-tables}

Sex-specific normative centile tables for HVR, hippocampal volume, and
lateral ventricular volume are provided in Supporting Information
(Tables S4--S9) to enable clinical interpretation of individual
measurements at 5-year age intervals. These tables allow clinicians to
determine an individual's percentile rank given their age, sex, and
brain measure.

GAMLSS model coefficients for the transfer models (excluding site random
effects) are provided in Table S10 and Table S11. These transfer models
enable researchers to compute individual centile scores in external
datasets where UK Biobank site identifiers are not applicable.

\subsection{Brain-Cognition
Associations}\label{brain-cognition-associations-1}

SEM analyses were restricted to the England subsample (N = 25,172) to
ensure comparability of the Index of Multiple Deprivation (IMDP)
covariate.

\subsubsection{Measurement Invariance}\label{measurement-invariance-1}

The cognitive bifactor model showed acceptable fit at all invariance
levels, with \(\Delta\)CFI \(\leq\) 0.01 and \(\Delta\)RMSEA \(\leq\)
0.015 at each step (Supporting Information, Table S12). Strict
measurement invariance was supported, validating cross-sex comparisons
of factor scores and structural paths.

\subsubsection{Pooled Model Results}\label{pooled-model-results}

General cognition (\emph{g}) was positively associated with all three
brain measures (Table~\ref{tbl-sem-paths}): unadjusted HC (\(\beta\) =
0.038 {[}95\% CI: 0.021, 0.055{]}), HVR (\(\beta\) = 0.043 {[}0.027,
0.059{]}), and HC\textsubscript{RES} (\(\beta\) = 0.027 {[}0.013,
0.042{]}), all p \textless{} .001. Confidence intervals overlapped
substantially, indicating no significant differences in predictive
validity between measures. HVR showed numerically the strongest
association with \emph{g}, despite requiring no head-size adjustment.

For processing speed (Speed\textsubscript{s}), HC showed the strongest
effect (\(\beta\) = 0.034, p = 0.017), followed by HC\textsubscript{RES}
(\(\beta\) = 0.028, p = 0.027), with HVR not significant (\(\beta\) =
0.008, p = 0.545). The memory-specific factor (Memory\textsubscript{s})
could not be reliably estimated in either sex and is therefore not
reported here (see Table S15 for factor loadings).

\begin{table}

\caption{\label{tbl-sem-paths}\textbf{Pooled brain-cognition path
coefficients.} Beta = standardized path coefficient; CI from 2000
bootstrap resamples. Memory-specific factor paths not shown due to
factor collapse.}

\centering{

\fontsize{7.0pt}{8.0pt}\selectfont
\begin{center}\renewcommand{\arraystretch}{1.15}\begin{tabular}{lrrr}
\toprule
Path & \ensuremath{\beta} & 95\% CI & p \\ 
\midrule\addlinespace[2.5pt]
\multicolumn{4}{l}{HVR} \\[2.5pt] 
\midrule\addlinespace[2.5pt]
\textrightarrow g & {\bfseries 0.043} & {\bfseries [0.027, 0.059]} & {\bfseries 1.14e-07} \\ 
\textrightarrow Speed\textsubscript{s} & 0.008 & [-0.018, 0.034] & 0.545 \\ 
\midrule\addlinespace[2.5pt]
\multicolumn{4}{l}{HC (Residualized)} \\[2.5pt] 
\midrule\addlinespace[2.5pt]
\textrightarrow g & {\bfseries 0.027} & {\bfseries [0.013, 0.042]} & {\bfseries 3.03e-04} \\ 
\textrightarrow Speed\textsubscript{s} & {\bfseries 0.028} & {\bfseries [0.003, 0.052]} & {\bfseries 0.027} \\ 
\midrule\addlinespace[2.5pt]
\multicolumn{4}{l}{HC (Unadjusted)} \\[2.5pt] 
\midrule\addlinespace[2.5pt]
\textrightarrow g & {\bfseries 0.038} & {\bfseries [0.021, 0.055]} & {\bfseries 1.04e-05} \\ 
\textrightarrow Speed\textsubscript{s} & {\bfseries 0.034} & {\bfseries [0.006, 0.062]} & {\bfseries 0.017} \\ 
\bottomrule
\end{tabular}\end{center}

}

\end{table}%

\subsubsection{Sex-Stratified Results}\label{sex-stratified-results}

Figure~\ref{fig-sem-forest} displays sex-stratified path coefficients
from multi-group models (detailed in Table S13). The multigroup analyses
revealed sex differences in brain-cognition associations.

For general cognition (\emph{g}), HC\textsubscript{RES} → \emph{g} was
not significant in males (p = 0.142) while remaining significant in
females. In contrast, HVR showed the opposite pattern: males exhibited
stronger HVR-cognition associations (\(\beta\) = 0.043) than females
(\(\beta\) = 0.038), with both significant. For processing speed
(Speed\textsubscript{s}), males showed significant HC and
HC\textsubscript{RES} associations (\(\beta\) = 0.065 and 0.056,
respectively) while females showed none, suggesting sex-differential
neural substrates for processing speed performance. Neither sex showed
significant HVR → Speed\textsubscript{s} associations.

\begin{figure}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{manuscript_files/figure-pdf/fig-sem-forest-1.pdf}}

}

\caption{\label{fig-sem-forest}\textbf{Brain-cognition paths by sex.}
Points represent standardized coefficients; lines show 95\% bootstrap
confidence intervals. White-filled points indicate non-significant
effects.}

\end{figure}%

All SEM models demonstrated good fit according to conventional criteria
(Table S14; Hu \& Bentler (1999)). Full model parameters including
factor loadings and covariate effects are reported in Table S15 and
Table S16.

\paragraph{Non-Linear Age Effects}\label{non-linear-age-effects}

As described in Methods, quadratic age terms were included in HVR and
HC\textsubscript{RES} models but not in the HC model due to
multicollinearity; fit indices for the HC model (Table S14) therefore
reflect a linear-age specification. All quadratic age effects were
significantly negative (all p \textless{} .001; Table S16), indicating
that cross-sectional differences between older and younger participants
were disproportionately larger at older ages. HVR showed a stronger
quadratic effect (\(\beta\) = -0.134) than HC\textsubscript{RES}
(\(\beta\) = -0.075; Table S16), consistent with HVR capturing both
hippocampal and ventricular age-related changes, both of which
accelerate at older ages. Cognitive factors showed comparable quadratic
effects across models (\emph{g}: \(\beta\) \(\approx\) -0.074;
Speed\textsubscript{s}: \(\beta\) \(\approx\) -0.028).

\subsection{Sensitivity Analyses}\label{sensitivity-analyses-1}

\subsubsection{Site-Adjusted Effect
Sizes}\label{site-adjusted-effect-sizes}

Site ICCs ranged from 0.004 to 0.012 (Supporting Information, Table
S17), indicating that scanner site explained less than 1.5\% of total
variance in all brain measures. Effect sizes remained consistent after
site adjustment.

\subsubsection{Hemisphere Comparison}\label{hemisphere-comparison-1}

Sex differences by hemisphere are reported in Table S18 and Figure S3.
Lateral ventricles showed a consistent male advantage with nearly
identical effect sizes across hemispheres (left d = -0.14, right d =
-0.16), and HVR showed a symmetric female advantage (left d = 0.48,
right d = 0.48). Residualized hippocampal volume showed a small
right-lateralized pattern: the left hemisphere effect was
non-significant (d = -0.01 {[}-0.03, 0.02{]}) while the right hemisphere
reached a small female advantage (d = 0.05 {[}0.03, 0.07{]}). The
bilateral consistency of LV and HVR supports the use of bilateral
measures rather than hemisphere-specific values for clinical
application.

\subsubsection{Inclusion of Psychiatric Diagnoses
(F-Codes)}\label{inclusion-of-psychiatric-diagnoses-f-codes}

Effect sizes remained stable when including participants with
psychiatric diagnoses (N = 30,032; Table S19, Figure S4), demonstrating
robustness of findings to exclusion criteria.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\section{Discussion}\label{discussion}

\subsection{Summary of Findings}\label{summary-of-findings}

In 27,680 UK Biobank participants, we evaluated HVR as a
self-normalizing measure that bypasses conventional head-size
correction. HVR showed weak correlation with ICV, substantially reducing
head-size dependence compared to unadjusted HC. Hippocampal sex
differences ranged from d = -0.89 (males larger) to d = 0.58 (females
larger) depending solely on the adjustment method and age, whereas HVR
consistently showed a female advantage replicated in the ICV-matched
subsample. Males showed steeper age-related HVR differences (1.66×
female slope), with the female advantage widening at older ages (d =
0.23 at 45-55y to d = 0.66 at 75+y). HVR predicted general cognition
comparably to hippocampal volume.

\subsection{Sex Differences Across Adjustment
Methods}\label{sex-differences-across-adjustment-methods-1}

HVR achieves head-size independence through its mathematical
construction: both numerator (HC) and denominator (HC + LV) scale with
head size, so their ratio largely normalizes out this confound.
Schoemaker et al. (2019) demonstrated that HVR yielded stronger
correlations with both age and memory performance than absolute
hippocampal volume, supporting its utility as an integrity index. In the
present sample, HVR achieved a 58\% reduction in ICV correlation
compared to unadjusted HC (r = -0.252 vs.~r = 0.605). This approach
complements other ratio measures in clinical neuroimaging, such as the
Evans' index (Currà et al., 2019), and avoids the pitfalls of
proportional ICV correction when brain structures scale
non-isometrically with head size (Pintzka et al., 2015; Wang et al.,
2024). The residual negative HVR-ICV correlation likely reflects
ventricular scaling: the hippocampus scales hypoallometrically with ICV
while lateral ventricles scale near-isometrically (Jong et al., 2017),
so larger heads have disproportionately larger ventricles relative to
hippocampal volume, naturally producing lower HVR. Unlike
residualization, which removes all ICV association by construction, HVR
preserves morphological variation related to how ventricular space
scales with brain size.

The reversal of HC sex differences across adjustment methods---from d =
-0.89 (males larger, unadjusted) to d = 0.58 (females larger,
proportions-adjusted), a swing of 1.47 SD---indicates these differences
reflect head-size confounding rather than biology. This over-correction
arises because the hippocampus scales hypoallometrically with ICV
(\(\alpha\) = 0.60; Jong et al. (2017)), so dividing by ICV
systematically overestimates relative volume in smaller heads (Pintzka
et al., 2015; Voevodskaya et al., 2014). The pattern replicates across
multiple cohorts (Fjell et al., 2009; Pintzka et al., 2015; Voevodskaya
et al., 2014), and Ritchie et al. (2018) reported that unadjusted
hippocampal sex differences in the UK Biobank dropped to near-zero after
regression-based adjustment. The near-zero residualized effect (d =
0.022) suggests no meaningful sex difference after appropriate
statistical control. While total hippocampal volume sex differences
appear methodologically determined, sex-specific trajectories in
hippocampal subregions (Mu et al., 2020) and structural connectivity
patterns (Ingalhalikar et al., 2014) suggest meaningful differences may
exist at finer spatial scales. Lateral ventricles, by contrast, showed a
consistent male advantage across all methods
(Figure~\ref{fig-effect-sizes}). Because the LV-ICV regression has a
negative y-intercept, proportional correction under-corrects rather than
over-corrects ventricular volumes---the opposite of what occurs for HC
(Pintzka et al., 2015). The male advantage persists or increases after
correction (Fjell et al., 2009), and in our large sample, residualized
LV differences remained significant (d = -0.16), suggesting that null
findings in smaller studies may reflect insufficient power. The
consistent male ventricular advantage contrasts sharply with the
method-dependent HC reversals, indicating this sex difference is not a
head-size artifact.

The matched-pair analysis (Table~\ref{tbl-matched}) provides the
strongest test of head-size independence. Matching on age and ICV
eliminates head-size variation without the mathematical assumptions of
statistical correction (Brzezinski-Rittner et al., 2025). When matched,
the HC sex difference collapsed to d = -0.038 (effectively zero),
replicating prior matched-sample findings (Pintzka et al., 2015;
Voevodskaya et al., 2014), while LV retained a male advantage (d = -0.2)
and HVR retained a significant female advantage (d = 0.183). The HVR
effect decreased 65\% from full to matched samples, indicating that most
of the sex difference is attributable to head-size variation, but a
significant residual persists. Since HVR = HC/(HC+LV), the female
advantage arises from two converging factors: comparable hippocampal
volumes after size matching and relatively smaller female ventricles.
This convergence---HC collapsing while LV and HVR effects survive ICV
matching---confirms that the female HVR advantage reflects genuine sex
differences in the hippocampus-to-ventricle balance, not head-size
confounding.

\subsection{Age-Related Patterns and Normative
Modeling}\label{age-related-patterns-and-normative-modeling-1}

Males showed steeper cross-sectional differences across all measures:
1.66× for HVR (p = 2e-61), 1.63× for HC, and 1.87× for LV, consistent
with steeper male subcortical decline reported by Ritchie et al. (2018)
and steeper male CSF expansion by Fjell et al. (2009). The greater sex
disparity in ventricular differences (1.87×) compared to hippocampal
differences (1.63×) explains HVR's intermediate ratio: HVR captures both
processes, and steeper male ventricular expansion amplifies hippocampal
differences. Males also show earlier ventricular abnormality signatures,
with ventricular enlargement accelerating in the seventies (Currà et
al., 2019), consistent with the steeper male HVR differences observed
here. While the cross-sectional design precludes identifying a specific
onset age, our age-stratified effect sizes show the male-female HVR
divergence is already present in the youngest bin (ages 45--55, d =
0.23) and widens monotonically with age (d = 0.66 at ages 75+),
suggesting the divergence begins before midlife. However,
Brzezinski-Rittner et al. (2025) found that hippocampal age × sex
interactions disappeared in a TIV-matched subsample, suggesting that
some sex-differential aging trajectories may be byproducts of initial
brain size differences.

The prognostic relevance of age-pattern differences is supported by
evidence that steeper hippocampal volume loss predicts dementia
conversion (Rajagopal et al., 2024). Cumulative estrogen exposure may
contribute to the female advantage, as longer reproductive spans are
associated with younger brain ages (Luders et al., 2025) and estrogen
promotes hippocampal neurogenesis and synaptic plasticity (Jett et al.,
2022). However, the female advantage is not universal: female APOE ε4
carriers show faster hippocampal loss than male carriers in amnestic MCI
(Park et al., 2025), indicating that genetic risk can modulate typical
sex-differential patterns. Other large studies have found no significant
sex differences in hippocampal age slopes (Fjell et al., 2009; Pintzka
et al., 2015), underscoring that the presence of age × sex interactions
depends on sample size, age range, and head-size adjustment method.
These cross-sectional patterns cannot establish true individual
trajectories and may be confounded by cohort effects or differential
survival; longitudinal validation is essential.

The sex-specific centile curves (Figure~\ref{fig-normative-centiles})
extend normative brain charts (Bethlehem et al., 2022; Dima et al.,
2022; Ge et al., 2024) by providing the first sex-specific reference
values for HVR. Our GAMLSS approach aligns with Bethlehem et al. (2022)
and Dima et al. (2022), flexibly modeling both non-linear age trends and
age-related variability changes. Sex-specific norms are essential to
avoid misclassification, consistent with recommendations from Williams
et al. (2021) and Ge et al. (2024), who found that sex accounts for a
considerable proportion of morphological variance. For residualized HC,
sex differences in centiles are minimal, consistent with the near-zero
Cohen's d for residualized volumes, supporting combined norms when
proper ICV adjustment is applied. For LV, males show greater ventricular
variability at older ages, potentially reflecting greater heterogeneity
in aging-related patterns. HVR showed slightly lower test-retest
reliability (ICC \textgreater{} 0.93; Table S3) than HC or LV alone over
a mean 2.7-year follow-up. Because this interval spans real
aging-related change, the lower ICC may partly reflect HVR's sensitivity
to concurrent hippocampal atrophy and ventricular expansion rather than
measurement noise alone --- a hypothesis that dedicated longitudinal
studies with shorter retest intervals could directly test.

\subsection{Brain-Cognition
Associations}\label{brain-cognition-associations-2}

Strict measurement invariance for the cognitive bifactor model
(\(\Delta\)CFI \(\leq\) 0.01 and \(\Delta\)RMSEA \(\leq\) 0.015 at each
level; Table S12) confirmed that the same cognitive constructs
(\emph{g}, Memory\textsubscript{s}, Speed\textsubscript{s}) exist in
both sexes with equivalent loadings, intercepts, and residual variances
(Chen, 2007; Putnick \& Bornstein, 2016), validating cross-sex
comparison of brain-cognition paths. In pooled models, HVR predicted
general cognition comparably to HC without requiring head-size
adjustment (HVR → \emph{g} \(\beta\) = 0.043 vs.~HC → \emph{g} \(\beta\)
= 0.038, overlapping CIs), with all effects small---consistent with the
modest brain-cognition associations typically observed in large healthy
samples (Ritchie et al., 2018; Wang et al., 2024). The restricted
cognitive range in healthy volunteer samples likely attenuates these
associations (Bachmann et al., 2023). Multigroup analyses revealed
sex-differential patterns: HC\textsubscript{RES} predicted cognition in
females but not males (\(\beta\) = 0.017, p = 0.142), consistent with
stronger female hippocampal-cognition associations reported elsewhere
(Jockwitz et al., 2024; Zheng et al., 2017). Raw HC showed significant
associations in both sexes but with a female advantage (\(\beta\) = 0.05
vs.~0.028). HVR showed the opposite pattern, with males exhibiting
stronger associations (\(\beta\) = 0.043 vs.~0.038), though both sexes
reached significance.

These sex-differential patterns indicate that HVR is not simply
``residualized HC by another means.'' Unlike HC\textsubscript{RES},
which lost predictive validity in males, HVR maintained significant
associations in both sexes---paralleling Schoemaker et al. (2019) and
Fernandez-Lozano et al. (2025), who found that HVR predicted cognition
comparably or better than HC alone. The differential patterns between
HC\textsubscript{RES} and HVR across sexes suggest HVR captures distinct
information related to hippocampus-ventricle coupling. HVR also
accommodated quadratic age specifications that raw HC could not (the HC
+ ICV + age² combination produced multicollinearity), allowing detection
of accelerating age-related patterns (\(\beta\)\textsubscript{age²} =
-0.134 for HVR vs.~-0.075 for HC\textsubscript{RES}). The stronger
quadratic effect for HVR reflects its capture of both hippocampal and
ventricular age-related differences. The ventricular component likely
contributes cognitive-relevant variance beyond medial temporal
integrity, as ventricular volume has been associated with executive
function rather than episodic memory (Bachmann et al., 2023).

\subsection{Sensitivity Analyses}\label{sensitivity-analyses-2}

Low site ICCs (all \textless{} 0.05; Table S17) confirmed minimal
scanner site contribution to variance, and effect sizes were stable
after site adjustment; the ratio construction of HVR did not amplify
site-related noise. Sex difference effect sizes were symmetric across
hemispheres for LV and HVR; residualized HC showed a small
right-lateralized pattern (right d = 0.05 vs.~left d = -0.01
non-significant), though the small magnitude and potential contribution
of hemispheric segmentation biases (Fernandez-Lozano et al., 2025)
suggest bilateral measures remain most robust for clinical application.
Including participants with psychiatric diagnoses changed effect sizes
minimally (\(\Delta\)d \textless{} 0.02; Table S19, Figure S4),
consistent with the low prevalence of psychiatric diagnoses in this
healthy volunteer cohort (Fry et al., 2017).

\subsection{Limitations}\label{limitations}

Design and sample constraints include the cross-sectional design, which
cannot distinguish age effects from cohort effects or establish
individual change trajectories, and HVR's conflation of hippocampal and
ventricular contributions to observed differences. UK Biobank
participants are healthier and more educated than the general population
(Fry et al., 2017), limiting generalizability to clinical populations.
Some cognitive tests had incomplete data, and complete-case analyses may
introduce selection bias. APOE genotype was unavailable, precluding
examination of gene × sex interactions relevant to dementia risk. The
final analytic sample is 56.2\% female; because GAMLSS normative models
were fit separately by sex, this imbalance does not bias the within-sex
centile curves.

Methodologically, the study did not include power-corrected proportions
allometric adjustment (Sanchis-Segura et al., 2020). Imaging site
clustering was not modeled in multigroup SEM because lavaan does not
support this combination (Rosseel, 2012), though the minimal design
effect across 4 sites makes sex comparisons conservative rather than
biased. The bifactor model's memory-specific factor could not be
reliably estimated in either sex---a common occurrence in bifactor
models (Burns et al., 2020; Eid et al., 2017)---indicating that memory
variance was fully captured by \emph{g}; brain-cognition paths involving
Memory\textsubscript{s} are therefore not reported. Ratios can exhibit
non-normality and complex interpretation when numerator and denominator
correlate differently with outcomes; HVR was only moderately skewed here
rather than markedly non-normal, and the normative models used a
distribution family (BCCG) that explicitly accommodates skewness. All
brain-cognition associations were small (all \(\beta\) \textless{}
0.07), explaining less than 1\% of variance in cognitive performance.
While statistically significant given the large sample, the practical
and clinical significance of these associations remains to be
established.

\subsection{Future Directions}\label{future-directions}

The current findings motivate four lines of follow-up work. First, the
UK Biobank repeat imaging subsample enables longitudinal validation of
whether HVR predicts individual-level cognitive decline. Second,
clinical validation in AD/MCI cohorts would assess HVR's diagnostic
utility compared to clinical populations studied previously
(Fernandez-Lozano et al., 2025). Third, longitudinal data could separate
hippocampal and ventricular contributions to HVR changes, which the
cross-sectional ratio conflates. Fourth, examining whether HVR × sex ×
APOE genotype predicts dementia conversion would address the gene × sex
interactions that this study could not explore.

\section{Conclusions}\label{conclusions}

In 27,680 UK Biobank participants (56.2\% female), hippocampal sex
differences reversed direction across adjustment methods (d range: 1.5
SD), confirming their methodological determination. HVR demonstrated
substantial head-size independence (r\textsubscript{ICV} = -0.25; 58\%
reduction vs.~raw HC) and a consistent female advantage replicated in
the ICV-matched subsample (d = 0.18). Males showed 1.66× steeper
age-related HVR differences (p = 2e-61); sex-specific normative centile
curves are provided for research application, pending validation in
clinical populations. HVR predicted general cognition comparably to
hippocampal volume (HVR → \emph{g}: \(\beta\) = 0.043 vs.~HC → \emph{g}:
\(\beta\) = 0.038, overlapping CIs), maintained predictive validity in
both sexes while residualized HC lost significance in males (p = 0.142),
and supported more complex SEM specifications that raw HC could not.

\section*{Author Contributions}\label{author-contributions}
\addcontentsline{toc}{section}{Author Contributions}

S.F-L. conceived the study, developed the analysis pipeline, performed
all analyses, and wrote the manuscript. D.L.C. supervised the project,
provided critical review, and approved the final manuscript.

\section*{Acknowledgments}\label{acknowledgments}
\addcontentsline{toc}{section}{Acknowledgments}

This research has been conducted using the UK Biobank Resource under
Application Number 45551.

This investigation was supported in part by an award from the
International Progressive MS Alliance (award reference number
PA-1412-02420), a grant from the Canadian Institutes of Health Research
{[}Project Grant FRN 205819{]}, and a donation from the Famille Louise
\& Andre Charron. The funders had no role in study design, data
collection and analysis, decision to publish, or preparation of the
manuscript.

\section*{Conflict of Interest
Statement}\label{conflict-of-interest-statement}
\addcontentsline{toc}{section}{Conflict of Interest Statement}

The authors declare no conflicts of interest.

\section*{Data Availability
Statement}\label{data-availability-statement}
\addcontentsline{toc}{section}{Data Availability Statement}

This research was conducted using UK Biobank data (Application 45551).
Data are available to approved researchers through the UK Biobank Access
Management System (https://www.ukbiobank.ac.uk/). Analysis code is
available at https://github.com/soffiafdz/hvr-sex-differences.

\section*{Ethics Approval Statement}\label{ethics-approval-statement}
\addcontentsline{toc}{section}{Ethics Approval Statement}

UK Biobank received ethical approval from the North West Multi-centre
Research Ethics Committee (REC reference: 16/NW/0274). All participants
provided written informed consent.

\section*{References}\label{references}
\addcontentsline{toc}{section}{References}

\phantomsection\label{refs}
\begin{CSLReferences}{1}{0}
\bibitem[\citeproctext]{ref-alfaro-almagro_image_2018}
Alfaro-Almagro, F., Jenkinson, M., Bangerter, N. K., Andersson, J. L.
R., Griffanti, L., Douaud, G., Sotiropoulos, S. N., Jbabdi, S.,
Hernandez-Fernandez, M., Vallee, E., Vidaurre, D., Webster, M.,
McCarthy, P., Rorden, C., Daducci, A., Alexander, D. C., Zhang, H.,
Dragonu, I., Matthews, P. M., \ldots{} Smith, S. M. (2018). Image
processing and {Quality} {Control} for the first 10,000 brain imaging
datasets from {UK} {Biobank}. \emph{NeuroImage}, \emph{166}, 400--424.
\url{https://doi.org/10.1016/j.neuroimage.2017.10.034}

\bibitem[\citeproctext]{ref-bachmann_age-_2023}
Bachmann, D., Buchmann, A., Studer, S., Saake, A., Rauen, K., Zuber, I.,
Gruber, E., Nitsch, R. M., Hock, C., Gietl, A., \& Treyer, V. (2023).
Age-, sex-, and pathology-related variability in brain structure and
cognition. \emph{Translational Psychiatry}, \emph{13}(1), 278.
\url{https://doi.org/10.1038/s41398-023-02572-6}

\bibitem[\citeproctext]{ref-bethlehem_brain_2022}
Bethlehem, R. a. I., Seidlitz, J., White, S. R., Vogel, J. W., Anderson,
K. M., Adamson, C., Adler, S., Alexopoulos, G. S., Anagnostou, E.,
Areces-Gonzalez, A., Astle, D. E., Auyeung, B., Ayub, M., Bae, J., Ball,
G., Baron-Cohen, S., Beare, R., Bedford, S. A., Benegal, V., \ldots{}
Alexander-Bloch, A. F. (2022). Brain charts for the human lifespan.
\emph{Nature}, \emph{604}(7906), 525--533.
\url{https://doi.org/10.1038/s41586-022-04554-y}

\bibitem[\citeproctext]{ref-brosch_reduced_2022}
Brosch, K., Stein, F., Schmitt, S., Pfarr, J.-K., Ringwald, K. G.,
Thomas-Odenthal, F., Meller, T., Steinsträter, O., Waltemate, L., Lemke,
H., Meinert, S., Winter, A., Breuer, F., Thiel, K., Grotegerd, D., Hahn,
T., Jansen, A., Dannlowski, U., Krug, A., \ldots{} Kircher, T. (2022).
Reduced hippocampal gray matter volume is a common feature of patients
with major depression, bipolar disorder, and schizophrenia spectrum
disorders. \emph{Molecular Psychiatry}, \emph{27}(10), 4234--4243.
\url{https://doi.org/10.1038/s41380-022-01687-4}

\bibitem[\citeproctext]{ref-brzezinski-rittner_disentangling_2025}
Brzezinski-Rittner, A., Moqadam, R., Iturria-Medina, Y., Chakravarty, M.
M., Dadar, M., \& Zeighami, Y. (2025). Disentangling the effect of sex
from brain size on brain organization and cognitive functioning.
\emph{GeroScience}, \emph{47}(1), 247--262.
\url{https://doi.org/10.1007/s11357-024-01486-5}

\bibitem[\citeproctext]{ref-burns_application_2020}
Burns, G. L., Geiser, C., Servera, M., Becker, S. P., \& Beauchaine, T.
P. (2020). Application of the {Bifactor} {S} -- 1 {Model} to
{Multisource} {Ratings} of {ADHD}/{ODD} {Symptoms}:{An} {Appropriate}
{Bifactor} {Model} for {Symptom} {Ratings}. \emph{Journal of Abnormal
Child Psychology}, \emph{48}(7), 881--894.
\url{https://doi.org/10.1007/s10802-019-00608-4}

\bibitem[\citeproctext]{ref-cao_volumes_2023}
Cao, P., Chen, C., Si, Q., Li, Y., Ren, F., Han, C., Zhao, J., Wang, X.,
Xu, G., \& Sui, Y. (2023). Volumes of hippocampal subfields suggest a
continuum between schizophrenia, major depressive disorder and bipolar
disorder. \emph{Frontiers in Psychiatry}, \emph{14}, 1191170.
\url{https://doi.org/10.3389/fpsyt.2023.1191170}

\bibitem[\citeproctext]{ref-chen_sensitivity_2007}
Chen, F. F. (2007). Sensitivity of {Goodness} of {Fit} {Indexes} to
{Lack} of {Measurement} {Invariance}. \emph{Structural Equation
Modeling: A Multidisciplinary Journal}, \emph{14}(3), 464--504.
\url{https://doi.org/10.1080/10705510701301834}

\bibitem[\citeproctext]{ref-cheung_evaluating_2002}
Cheung, G. W., \& Rensvold, R. B. (2002). Evaluating {Goodness}-of-{Fit}
{Indexes} for {Testing} {Measurement} {Invariance}. \emph{Structural
Equation Modeling: A Multidisciplinary Journal}, \emph{9}(2), 233--255.
\url{https://doi.org/10.1207/S15328007SEM0902_5}

\bibitem[\citeproctext]{ref-cohen_statistical_2013}
Cohen, J. (2013). \emph{Statistical {Power} {Analysis} for the
{Behavioral} {Sciences}} (2nd ed.). Routledge.
\url{https://doi.org/10.4324/9780203771587}

\bibitem[\citeproctext]{ref-coupe_assemblynet_2020}
Coupé, P., Mansencal, B., Clément, M., Giraud, R., Denis de Senneville,
B., Ta, V.-T., Lepetit, V., \& Manjon, J. V. (2020). {AssemblyNet}: {A}
large ensemble of {CNNs} for {3D} whole brain {MRI} segmentation.
\emph{NeuroImage}, \emph{219}, 117026.
\url{https://doi.org/10.1016/j.neuroimage.2020.117026}

\bibitem[\citeproctext]{ref-cumming_inference_2005}
Cumming, G., \& Finch, S. (2005). Inference by {Eye}: {Confidence}
{Intervals} and {How} to {Read} {Pictures} of {Data}. \emph{American
Psychologist}, \emph{60}(2), 170--180.
\url{https://doi.org/10.1037/0003-066X.60.2.170}

\bibitem[\citeproctext]{ref-curra_ventricular_2019}
Currà, A., Pierelli, F., Gasbarrone, R., Mannarelli, D., Nofroni, I.,
Matone, V., Marinelli, L., Trompetto, C., Fattapposta, F., \& Missori,
P. (2019). The {Ventricular} {System} {Enlarges} {Abnormally} in the
{Seventies}, {Earlier} in {Men}, and {First} in the {Frontal} {Horn}:
{A} {Study} {Based} on {More} {Than} 3,000 {Scans}. \emph{Frontiers in
Aging Neuroscience}, \emph{11}.
\url{https://doi.org/10.3389/fnagi.2019.00294}

\bibitem[\citeproctext]{ref-dima_subcortical_2022}
Dima, D., Modabbernia, A., Papachristou, E., Doucet, G. E., Agartz, I.,
\& Karolinska Schizophrenia Project (KaSP). (2022). Subcortical volumes
across the lifespan: {Data} from 18,605 healthy individuals aged 3--90
years. \emph{Human Brain Mapping}, \emph{43}(1), 452--469.
\url{https://doi.org/10.1002/hbm.25320}

\bibitem[\citeproctext]{ref-eid_anomalous_2017}
Eid, M., Geiser, C., Koch, T., \& Heene, M. (2017). Anomalous results in
{G}-factor models: {Explanations} and alternatives. \emph{Psychological
Methods}, \emph{22}(3), 541--562.
\url{https://doi.org/10.1037/met0000083}

\bibitem[\citeproctext]{ref-van_erp_subcortical_2016}
Erp, T. G. M. van, Hibar, D. P., Rasmussen, J. M., Glahn, D. C.,
Pearlson, G. D., Andreassen, O. A., Agartz, I., Westlye, L. T., Haukvik,
U. K., Dale, A. M., Melle, I., Hartberg, C. B., Gruber, O., Kraemer, B.,
Zilles, D., Donohoe, G., Kelly, S., McDonald, C., Morris, D. W.,
\ldots{} Turner, J. A. (2016). Subcortical brain volume abnormalities in
2028 individuals with schizophrenia and 2540 healthy controls via the
{ENIGMA} consortium. \emph{Molecular Psychiatry}, \emph{21}(4),
547--553. \url{https://doi.org/10.1038/mp.2015.63}

\bibitem[\citeproctext]{ref-fernandez-lozano_enhanced_2025}
Fernandez-Lozano, S., Fonov, V., Schoemaker, D., Pruessner, J., Potvin,
O., Duchesne, S., Collins, D. L., \& Initiative, A. D. N. (2025).
Enhanced {Detection} of {Age}-{Related} and {Cognitive} {Declines}
{Using} {Automated} {Hippocampal}-{To}-{Ventricle} {Ratio} in
{Alzheimer}'s {Patients}. \emph{Human Brain Mapping}, \emph{46}(11),
e70265. \url{https://doi.org/10.1002/hbm.70265}

\bibitem[\citeproctext]{ref-fjell_minute_2009}
Fjell, A. M., Westlye, L. T., Amlien, I., Espeseth, T., Reinvang, I.,
Raz, N., Agartz, I., Salat, D. H., Greve, D. N., Fischl, B., Dale, A.
M., \& Walhovd, K. B. (2009). Minute {Effects} of {Sex} on the {Aging}
{Brain}: {A} {Multisample} {Magnetic} {Resonance} {Imaging} {Study} of
{Healthy} {Aging} and {Alzheimer}'s {Disease}. \emph{Journal of
Neuroscience}, \emph{29}(27), 8774--8783.
\url{https://doi.org/10.1523/JNEUROSCI.0115-09.2009}

\bibitem[\citeproctext]{ref-fonov_darq_2022}
Fonov, V., Dadar, M., Adni, T. P.-A. R. G., \& Collins, D. L. (2022).
{DARQ}: {Deep} learning of quality control for stereotaxic registration
of human brain {MRI} to the {T1w} {MNI}-{ICBM} 152 template.
\emph{NeuroImage}, \emph{257}, 119266.
\url{https://doi.org/10.1016/j.neuroimage.2022.119266}

\bibitem[\citeproctext]{ref-fry_comparison_2017}
Fry, A., Littlejohns, T. J., Sudlow, C., Doherty, N., Adamska, L.,
Sprosen, T., Collins, R., \& Allen, N. E. (2017). Comparison of
{Sociodemographic} and {Health}-{Related} {Characteristics} of {UK}
{Biobank} {Participants} {With} {Those} of the {General} {Population}.
\emph{American Journal of Epidemiology}, \emph{186}(9), 1026--1034.
\url{https://doi.org/10.1093/aje/kwx246}

\bibitem[\citeproctext]{ref-ge_normative_2024}
Ge, R., Yu, Y., Qi, Y. X., Fan, Y., Chen, S., Gao, C., Haas, S. S., New,
F., Boomsma, D. I., Brodaty, H., Brouwer, R. M., Buckner, R., Caseras,
X., Crivello, F., Crone, E. A., Erk, S., Fisher, S. E., Franke, B.,
Glahn, D. C., \ldots{} Yu, K. (2024). Normative modelling of brain
morphometry across the lifespan with {CentileBrain}: Algorithm
benchmarking and model optimisation. \emph{The Lancet Digital Health},
\emph{6}(3), e211--e221.
\url{https://doi.org/10.1016/S2589-7500(23)00250-9}

\bibitem[\citeproctext]{ref-ho_matchit_2011}
Ho, D., Imai, K., King, G., \& Stuart, E. A. (2011). {MatchIt}:
{Nonparametric} {Preprocessing} for {Parametric} {Causal} {Inference}.
\emph{Journal of Statistical Software}, \emph{42}, 1--28.
\url{https://doi.org/10.18637/jss.v042.i08}

\bibitem[\citeproctext]{ref-hu_cutoff_1999}
Hu, L., \& Bentler, P. M. (1999). Cutoff criteria for fit indexes in
covariance structure analysis: {Conventional} criteria versus new
alternatives. \emph{Structural Equation Modeling: A Multidisciplinary
Journal}, \emph{6}(1), 1--55.
\url{https://doi.org/10.1080/10705519909540118}

\bibitem[\citeproctext]{ref-ingalhalikar_sex_2014}
Ingalhalikar, M., Smith, A., Parker, D., Satterthwaite, T. D., Elliott,
M. A., Ruparel, K., Hakonarson, H., Gur, R. E., Gur, R. C., \& Verma, R.
(2014). Sex differences in the structural connectome of the human brain.
\emph{Proceedings of the National Academy of Sciences}, \emph{111}(2),
823--828. \url{https://doi.org/10.1073/pnas.1316909110}

\bibitem[\citeproctext]{ref-jack_hypothetical_2010}
Jack, C. R., Knopman, D. S., Jagust, W. J., Shaw, L. M., Aisen, P. S.,
Weiner, M. W., Petersen, R. C., \& Trojanowski, J. Q. (2010).
Hypothetical model of dynamic biomarkers of the {Alzheimer}'s
pathological cascade. \emph{The Lancet Neurology}, \emph{9}(1),
119--128. \url{https://doi.org/10.1016/S1474-4422(09)70299-6}

\bibitem[\citeproctext]{ref-jack_prediction_1999}
Jack, C. R., Petersen, R. C., Xu, Y. C., O'Brien, P. C., Smith, G. E.,
Ivnik, R. J., Boeve, B. F., Waring, S. C., Tangalos, E. G., \& Kokmen,
E. (1999). Prediction of {AD} with {MRI}-based hippocampal volume in
mild cognitive impairment. \emph{Neurology}, \emph{52}(7), 1397--1397.
\url{https://doi.org/10.1212/WNL.52.7.1397}

\bibitem[\citeproctext]{ref-jett_endogenous_2022}
Jett, S., Malviya, N., Schelbaum, E., Jang, G., Jahan, E., Clancy, K.,
Hristov, H., Pahlajani, S., Niotis, K., Loeb-Zeitlin, S., Havryliuk, Y.,
Isaacson, R., Brinton, R. D., \& Mosconi, L. (2022). Endogenous and
{Exogenous} {Estrogen} {Exposures}: {How} {Women}'s {Reproductive}
{Health} {Can} {Drive} {Brain} {Aging} and {Inform} {Alzheimer}'s
{Prevention}. \emph{Frontiers in Aging Neuroscience}, \emph{14}.
\url{https://doi.org/10.3389/fnagi.2022.831807}

\bibitem[\citeproctext]{ref-jockwitz_differential_2024}
Jockwitz, C., Krämer, C., Dellani, P., \& Caspers, S. (2024).
Differential predictability of cognitive profiles from brain structure
in older males and females. \emph{GeroScience}, \emph{46}(2),
1713--1730. \url{https://doi.org/10.1007/s11357-023-00934-y}

\bibitem[\citeproctext]{ref-de_jong_allometric_2017}
Jong, L. W. de, Vidal, J.-S., Forsberg, L. E., Zijdenbos, A. P., Haight,
T., Initiative, A. D. N., Sigurdsson, S., Gudnason, V., Buchem, M. A.
van, \& Launer, L. J. (2017). Allometric scaling of brain regions to
intra-cranial volume: {An} epidemiological {MRI} study. \emph{Human
Brain Mapping}, \emph{38}(1), 151--164.
\url{https://doi.org/10.1002/hbm.23351}

\bibitem[\citeproctext]{ref-koenig_hippocampal_2014}
Koenig, K. A., Sakaie, K. E., Lowe, M. J., Lin, J., Stone, L., Bermel,
R. A., Beall, E. B., Rao, S. M., Trapp, B. D., \& Phillips, M. D.
(2014). Hippocampal volume is related to cognitive decline and fornicial
diffusion measures in multiple sclerosis. \emph{Magnetic Resonance
Imaging}, \emph{32}(4), 354--358.
\url{https://doi.org/10.1016/j.mri.2013.12.012}

\bibitem[\citeproctext]{ref-luders_case_2025}
Luders, E., Poromaa, I. S., Barth, C., \& Gaser, C. (2025). A {Case} for
estradiol: Younger brains in women with earlier menarche and later
menopause. \emph{GigaScience}, \emph{14}, giaf060.
\url{https://doi.org/10.1093/gigascience/giaf060}

\bibitem[\citeproctext]{ref-madsen_mapping_2015}
Madsen, S. K., Gutman, B. A., Joshi, S. H., Toga, A. W., Jack, C. R.,
Weiner, M. W., \& Thompson, P. M. (2015). Mapping ventricular expansion
onto cortical gray matter in older adults. \emph{Neurobiology of Aging},
\emph{36}, S32--S41.
\url{https://doi.org/10.1016/j.neurobiolaging.2014.03.044}

\bibitem[\citeproctext]{ref-miller_multimodal_2016}
Miller, K. L., Alfaro-Almagro, F., Bangerter, N. K., Thomas, D. L.,
Yacoub, E., Xu, J., Bartsch, A. J., Jbabdi, S., Sotiropoulos, S. N.,
Andersson, J. L., Griffanti, L., Douaud, G., Okell, T. W., Weale, P.,
Dragonu, I., Garratt, S., Hudson, S., Collins, R., Jenkinson, M.,
\ldots{} Smith, S. M. (2016). Multimodal population brain imaging in the
{UK} {Biobank} prospective epidemiological study. \emph{Nature
Neuroscience}, \emph{19}(11), 1523--1536.
\url{https://doi.org/10.1038/nn.4393}

\bibitem[\citeproctext]{ref-mu_effect_2020}
Mu, S. H., Yuan, B. K., \& Tan, L. H. (2020). Effect of {Gender} on
{Development} of {Hippocampal} {Subregions} {From} {Childhood} to
{Adulthood}. \emph{Frontiers in Human Neuroscience}, \emph{14}, 611057.
\url{https://doi.org/10.3389/fnhum.2020.611057}

\bibitem[\citeproctext]{ref-nordenskjold_intracranial_2015}
Nordenskjöld, R., Malmberg, F., Larsson, E.-M., Simmons, A., Ahlström,
H., Johansson, L., \& Kullberg, J. (2015). Intracranial volume
normalization methods: {Considerations} when investigating gender
differences in regional brain volume. \emph{Psychiatry Research:
Neuroimaging}, \emph{231}(3), 227--235.
\url{https://doi.org/10.1016/j.pscychresns.2014.11.011}

\bibitem[\citeproctext]{ref-obrien_statistical_2011}
O'Brien, L. M., Ziegler, D. A., Deutsch, C. K., Frazier, J. A., Herbert,
M. R., \& Locascio, J. J. (2011). Statistical adjustments for brain size
in volumetric neuroimaging studies: {Some} practical implications in
methods. \emph{Psychiatry Research: Neuroimaging}, \emph{193}(2),
113--122. \url{https://doi.org/10.1016/j.pscychresns.2011.01.007}

\bibitem[\citeproctext]{ref-park_sex-specific_2025}
Park, C. H., Lee, H., Lee, Y.-M., Lee, B.-D., Moon, E., Suh, H., Kim,
K., Kim, H.-J., Shim, H., Pak, K., Choi, K.-U., \& Kim, C.-S. (2025).
Sex-specific effects of apolipoprotein {E} ε4 genotype on longitudinal
hippocampal atrophy in amnestic mild cognitive impairment over a 2-year
evaluation period. \emph{Journal of Alzheimer's Disease}, \emph{103}(4),
1269--1276. \url{https://doi.org/10.1177/13872877241313066}

\bibitem[\citeproctext]{ref-pintzka_marked_2015}
Pintzka, C. W. S., Hansen, T. I., Evensmoen, H. R., \& Håberg, A. K.
(2015). Marked effects of intracranial volume correction methods on sex
differences in neuroanatomical structures: A {HUNT} {MRI} study.
\emph{Frontiers in Neuroscience}, \emph{9}.
\url{https://doi.org/10.3389/fnins.2015.00238}

\bibitem[\citeproctext]{ref-putnick_measurement_2016}
Putnick, D. L., \& Bornstein, M. H. (2016). Measurement invariance
conventions and reporting: {The} state of the art and future directions
for psychological research. \emph{Developmental Review}, \emph{41},
71--90. \url{https://doi.org/10.1016/j.dr.2016.06.004}

\bibitem[\citeproctext]{ref-rajagopal_estimating_2024}
Rajagopal, S. K., Beltz, A. M., Hampstead, B. M., \& Polk, T. A. (2024).
Estimating individual trajectories of structural and cognitive decline
in mild cognitive impairment for early prediction of progression to
dementia of the {Alzheimer}'s type. \emph{Scientific Reports},
\emph{14}(1), 12906. \url{https://doi.org/10.1038/s41598-024-63301-7}

\bibitem[\citeproctext]{ref-raz_regional_2005}
Raz, N., Lindenberger, U., Rodrigue, K. M., Kennedy, K. M., Head, D.,
Williamson, A., Dahle, C., Gerstorf, D., \& Acker, J. D. (2005).
Regional {Brain} {Changes} in {Aging} {Healthy} {Adults}: {General}
{Trends}, {Individual} {Differences} and {Modifiers}. \emph{Cerebral
Cortex}, \emph{15}(11), 1676--1689.
\url{https://doi.org/10.1093/cercor/bhi044}

\bibitem[\citeproctext]{ref-rigby_generalized_2005}
Rigby, R. A., \& Stasinopoulos, D. M. (2005). Generalized {Additive}
{Models} for {Location}, {Scale} and {Shape}. \emph{Journal of the Royal
Statistical Society Series C: Applied Statistics}, \emph{54}(3),
507--554. \url{https://doi.org/10.1111/j.1467-9876.2005.00510.x}

\bibitem[\citeproctext]{ref-ritchie_sex_2018}
Ritchie, S. J., Cox, S. R., Shen, X., Lombardo, M. V., Reus, L. M.,
Alloza, C., Harris, M. A., Alderson, H. L., Hunter, S., Neilson, E.,
Liewald, D. C. M., Auyeung, B., Whalley, H. C., Lawrie, S. M., Gale, C.
R., Bastin, M. E., McIntosh, A. M., \& Deary, I. J. (2018). Sex
{Differences} in the {Adult} {Human} {Brain}: {Evidence} from 5216 {UK}
{Biobank} {Participants}. \emph{Cerebral Cortex (New York, NY)},
\emph{28}(8), 2959--2975. \url{https://doi.org/10.1093/cercor/bhy109}

\bibitem[\citeproctext]{ref-rosseel_lavaan_2012}
Rosseel, Y. (2012). Lavaan: {An} {R} {Package} for {Structural}
{Equation} {Modeling}. \emph{Journal of Statistical Software},
\emph{48}, 1--36. \url{https://doi.org/10.18637/jss.v048.i02}

\bibitem[\citeproctext]{ref-ruigrok_meta-analysis_2014}
Ruigrok, A. N. V., Salimi-Khorshidi, G., Lai, M.-C., Baron-Cohen, S.,
Lombardo, M. V., Tait, R. J., \& Suckling, J. (2014). A meta-analysis of
sex differences in human brain structure. \emph{Neuroscience \&
Biobehavioral Reviews}, \emph{39}, 34--50.
\url{https://doi.org/10.1016/j.neubiorev.2013.12.004}

\bibitem[\citeproctext]{ref-sanchis-segura_effects_2020}
Sanchis-Segura, C., Ibañez-Gual, M. V., Aguirre, N., Cruz-Gómez, Á. J.,
\& Forn, C. (2020). Effects of different intracranial volume correction
methods on univariate sex differences in grey matter volume and
multivariate sex prediction. \emph{Scientific Reports}, \emph{10}(1),
12953. \url{https://doi.org/10.1038/s41598-020-69361-9}

\bibitem[\citeproctext]{ref-sanfilipo_correction_2004}
Sanfilipo, M. P., Benedict, R. H. B., Zivadinov, R., \& Bakshi, R.
(2004). Correction for intracranial volume in analysis of whole brain
atrophy in multiple sclerosis: The proportion vs. Residual method.
\emph{NeuroImage}, \emph{22}(4), 1732--1743.
\url{https://doi.org/10.1016/j.neuroimage.2004.03.037}

\bibitem[\citeproctext]{ref-schmaal_subcortical_2016}
Schmaal, L., Veltman, D. J., Erp, T. G. M. van, Sämann, P. G., Frodl,
T., Jahanshad, N., Loehrer, E., Tiemeier, H., Hofman, A., Niessen, W.
J., Vernooij, M. W., Ikram, M. A., Wittfeld, K., Grabe, H. J., Block,
A., Hegenscheid, K., Völzke, H., Hoehn, D., Czisch, M., \ldots{} Hibar,
D. P. (2016). Subcortical brain alterations in major depressive
disorder: Findings from the {ENIGMA} {Major} {Depressive} {Disorder}
working group. \emph{Molecular Psychiatry}, \emph{21}(6), 806--812.
\url{https://doi.org/10.1038/mp.2015.69}

\bibitem[\citeproctext]{ref-schoemaker_hippocampal-ventricle_2019}
Schoemaker, D., Buss, C., Pietrantonio, S., Maunder, L., Freiesleben, S.
D., Hartmann, J., Collins, D. L., Lupien, S., \& Pruessner, J. C.
(2019). The hippocampal-to-ventricle ratio ({HVR}): {Presentation} of a
manual segmentation protocol and preliminary evidence.
\emph{NeuroImage}, \emph{203}, 116108.
\url{https://doi.org/10.1016/j.neuroimage.2019.116108}

\bibitem[\citeproctext]{ref-sudlow_uk_2015}
Sudlow, C., Gallacher, J., Allen, N., Beral, V., Burton, P., Danesh, J.,
Downey, P., Elliott, P., Green, J., Landray, M., Liu, B., Matthews, P.,
Ong, G., Pell, J., Silman, A., Young, A., Sprosen, T., Peakman, T., \&
Collins, R. (2015). {UK} biobank: An open access resource for
identifying the causes of a wide range of complex diseases of middle and
old age. \emph{PLoS Medicine}, \emph{12}(3), e1001779.
\url{https://doi.org/10.1371/journal.pmed.1001779}

\bibitem[\citeproctext]{ref-tai_detection_2025}
Tai, X. Y., Toniolo, S., Llewellyn, D. J., Van Duijn, C. M., Husain, M.,
\& Manohar, S. G. (2025). Detection of cognitive deficits years prior to
clinical diagnosis across neurological conditions. \emph{Brain
Communications}, \emph{7}(5), fcaf307.
\url{https://doi.org/10.1093/braincomms/fcaf307}

\bibitem[\citeproctext]{ref-voevodskaya_effects_2014}
Voevodskaya, O., Simmons, A., Nordenskjöld, R., Kullberg, J., Ahlström,
H., Lind, L., Wahlund, L.-O., Larsson, E.-M., Westman, E., \&
Alzheimer's Disease Neuroimaging Initiative. (2014). The effects of
intracranial volume adjustment approaches on multiple regional {MRI}
volumes in healthy aging and {Alzheimer}'s disease. \emph{Frontiers in
Aging Neuroscience}, \emph{6}.
\url{https://doi.org/10.3389/fnagi.2014.00264}

\bibitem[\citeproctext]{ref-wang_comparison_2024}
Wang, J., Hill-Jarrett, T., Buto, P., Pederson, A., Sims, K. D.,
Zimmerman, S. C., DeVost, M. A., Ferguson, E., Lacar, B., Yang, Y.,
Choi, M., Caunca, M. R., La Joie, R., Chen, R., Glymour, M. M., \&
Ackley, S. F. (2024). Comparison of approaches to control for
intracranial volume in research on the association of brain volumes with
cognitive outcomes. \emph{Human Brain Mapping}, \emph{45}(4), e26633.
\url{https://doi.org/10.1002/hbm.26633}

\bibitem[\citeproctext]{ref-williams_neuroanatomical_2021}
Williams, C. M., Peyre, H., Toro, R., \& Ramus, F. (2021).
Neuroanatomical norms in the {UK} {Biobank}: {The} impact of allometric
scaling, sex, and age. \emph{Human Brain Mapping}, \emph{42}(14),
4623--4642. \url{https://doi.org/10.1002/hbm.25572}

\bibitem[\citeproctext]{ref-xu_longitudinal_2020}
Xu, R., Hu, X., Jiang, X., Zhang, Y., Wang, J., \& Zeng, X. (2020).
Longitudinal volume changes of hippocampal subfields and cognitive
decline in {Parkinson}'s disease. \emph{Quantitative Imaging in Medicine
and Surgery}, \emph{10}(1), 220--232.
\url{https://doi.org/10.21037/qims.2019.10.17}

\bibitem[\citeproctext]{ref-zheng_sex_2017}
Zheng, Z., Li, R., Xiao, F., He, R., Zhang, S., \& Li, J. (2017). Sex
{Matters}: {Hippocampal} {Volume} {Predicts} {Individual} {Differences}
in {Associative} {Memory} in {Cognitively} {Normal} {Older} {Women} but
{Not} {Men}. \emph{Frontiers in Human Neuroscience}, \emph{11}.
\url{https://doi.org/10.3389/fnhum.2017.00093}

\end{CSLReferences}




\end{document}
